import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_generate_client = {"outputPath":"/output/client","files":["index.js","api.js"]};
const sample_validate_spec = {"valid":true,"errors":[],"warnings":["Missing description for /users"]};
const sample_generate_docs = {"outputPath":"/output/docs/index.html"};
const sample_convert_spec = {"outputPath":"/output/spec.yaml","format":"openapi3"};
describe('swagger-openapi-generator: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('swagger-openapi-generator: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail generate_client', async()=>{ const r=await execute({action:'generate_client',specUrl:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail validate_spec', async()=>{ const r=await execute({action:'validate_spec',specUrl:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail generate_docs', async()=>{ const r=await execute({action:'generate_docs',specUrl:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail convert_spec', async()=>{ const r=await execute({action:'convert_spec',specUrl:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('swagger-openapi-generator: generate_client', ()=>{beforeEach(()=>{});
  it('generate_client ok', async()=>{ const r=await execute({action:'generate_client',specUrl:'test'},mockContext(sample_generate_client)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'generate_client'); });
  it('generate_client missing', async()=>{ const r=await execute({action:'generate_client'},mockContext(sample_generate_client)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('generate_client non-str', async()=>{ const r=await execute({action:'generate_client',specUrl:123},mockContext(sample_generate_client)); assert.equal(r.metadata.success,false); });
});
describe('swagger-openapi-generator: validate_spec', ()=>{beforeEach(()=>{});
  it('validate_spec ok', async()=>{ const r=await execute({action:'validate_spec',specUrl:'test'},mockContext(sample_validate_spec)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'validate_spec'); });
  it('validate_spec missing', async()=>{ const r=await execute({action:'validate_spec'},mockContext(sample_validate_spec)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('validate_spec non-str', async()=>{ const r=await execute({action:'validate_spec',specUrl:123},mockContext(sample_validate_spec)); assert.equal(r.metadata.success,false); });
});
describe('swagger-openapi-generator: generate_docs', ()=>{beforeEach(()=>{});
  it('generate_docs ok', async()=>{ const r=await execute({action:'generate_docs',specUrl:'test'},mockContext(sample_generate_docs)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'generate_docs'); });
  it('generate_docs missing', async()=>{ const r=await execute({action:'generate_docs'},mockContext(sample_generate_docs)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('generate_docs non-str', async()=>{ const r=await execute({action:'generate_docs',specUrl:123},mockContext(sample_generate_docs)); assert.equal(r.metadata.success,false); });
});
describe('swagger-openapi-generator: convert_spec', ()=>{beforeEach(()=>{});
  it('convert_spec ok', async()=>{ const r=await execute({action:'convert_spec',specUrl:'test'},mockContext(sample_convert_spec)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'convert_spec'); });
  it('convert_spec missing', async()=>{ const r=await execute({action:'convert_spec'},mockContext(sample_convert_spec)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('convert_spec non-str', async()=>{ const r=await execute({action:'convert_spec',specUrl:123},mockContext(sample_convert_spec)); assert.equal(r.metadata.success,false); });
});
describe('swagger-openapi-generator: timeout', ()=>{beforeEach(()=>{});
  it('to generate_client', async()=>{ const r=await execute({action:'generate_client',specUrl:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to validate_spec', async()=>{ const r=await execute({action:'validate_spec',specUrl:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to generate_docs', async()=>{ const r=await execute({action:'generate_docs',specUrl:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to convert_spec', async()=>{ const r=await execute({action:'convert_spec',specUrl:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('swagger-openapi-generator: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'generate_client',specUrl:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'generate_client',specUrl:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('swagger-openapi-generator: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('swagger-openapi-generator: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('swagger-openapi-generator: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('swagger-openapi-generator: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('generate_client req', ()=>{ assert.equal(validate({action:'generate_client'}).valid,false); assert.equal(validate({action:'generate_client',specUrl:'t'}).valid,true); });
  it('validate_spec req', ()=>{ assert.equal(validate({action:'validate_spec'}).valid,false); assert.equal(validate({action:'validate_spec',specUrl:'t'}).valid,true); });
  it('generate_docs req', ()=>{ assert.equal(validate({action:'generate_docs'}).valid,false); assert.equal(validate({action:'generate_docs',specUrl:'t'}).valid,true); });
  it('convert_spec req', ()=>{ assert.equal(validate({action:'convert_spec'}).valid,false); assert.equal(validate({action:'convert_spec',specUrl:'t'}).valid,true); });
});
describe('swagger-openapi-generator: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'swagger-openapi-generator');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('swagger-openapi-generator: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_generate_client},config:{timeoutMs:5000}};const r=await execute({action:'generate_client',specUrl:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('swagger-openapi-generator: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('swagger-openapi-generator: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['generate_client','validate_spec','generate_docs','convert_spec']);});
});
describe('swagger-openapi-generator: paths', ()=>{beforeEach(()=>{});
  it('path generate_client', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_generate_client;}},config:{timeoutMs:5000}}; await execute({action:'generate_client',specUrl:'test'},ctx); assert.ok(p!==null); });
  it('path validate_spec', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_validate_spec;}},config:{timeoutMs:5000}}; await execute({action:'validate_spec',specUrl:'test'},ctx); assert.ok(p!==null); });
  it('path generate_docs', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_generate_docs;}},config:{timeoutMs:5000}}; await execute({action:'generate_docs',specUrl:'test'},ctx); assert.ok(p!==null); });
  it('path convert_spec', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_convert_spec;}},config:{timeoutMs:5000}}; await execute({action:'convert_spec',specUrl:'test'},ctx); assert.ok(p!==null); });
});
