import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_validate_email = {"email":"test@example.com","valid":true,"disposable":false,"mxRecords":true};
const sample_bulk_validate = {"results":[{"email":"a@b.com","valid":true}],"validCount":1,"invalidCount":0};
const sample_check_domain = {"domain":"example.com","mxRecords":["mx1.example.com"],"valid":true};
const sample_get_suggestions = {"original":"test@gmial.com","suggestion":"test@gmail.com","confidence":0.95};
describe('email-validator: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('email-validator: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail validate_email', async()=>{ const r=await execute({action:'validate_email',email:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail bulk_validate', async()=>{ const r=await execute({action:'bulk_validate',emails:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail check_domain', async()=>{ const r=await execute({action:'check_domain',domain:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_suggestions', async()=>{ const r=await execute({action:'get_suggestions',email:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('email-validator: validate_email', ()=>{beforeEach(()=>{});
  it('validate_email ok', async()=>{ const r=await execute({action:'validate_email',email:'test'},mockContext(sample_validate_email)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'validate_email'); });
  it('validate_email missing', async()=>{ const r=await execute({action:'validate_email'},mockContext(sample_validate_email)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('validate_email non-str', async()=>{ const r=await execute({action:'validate_email',email:123},mockContext(sample_validate_email)); assert.equal(r.metadata.success,false); });
});
describe('email-validator: bulk_validate', ()=>{beforeEach(()=>{});
  it('bulk_validate ok', async()=>{ const r=await execute({action:'bulk_validate',emails:'test'},mockContext(sample_bulk_validate)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'bulk_validate'); });
  it('bulk_validate missing', async()=>{ const r=await execute({action:'bulk_validate'},mockContext(sample_bulk_validate)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('bulk_validate non-str', async()=>{ const r=await execute({action:'bulk_validate',emails:123},mockContext(sample_bulk_validate)); assert.equal(r.metadata.success,false); });
});
describe('email-validator: check_domain', ()=>{beforeEach(()=>{});
  it('check_domain ok', async()=>{ const r=await execute({action:'check_domain',domain:'test'},mockContext(sample_check_domain)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'check_domain'); });
  it('check_domain missing', async()=>{ const r=await execute({action:'check_domain'},mockContext(sample_check_domain)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('check_domain non-str', async()=>{ const r=await execute({action:'check_domain',domain:123},mockContext(sample_check_domain)); assert.equal(r.metadata.success,false); });
});
describe('email-validator: get_suggestions', ()=>{beforeEach(()=>{});
  it('get_suggestions ok', async()=>{ const r=await execute({action:'get_suggestions',email:'test'},mockContext(sample_get_suggestions)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_suggestions'); });
  it('get_suggestions missing', async()=>{ const r=await execute({action:'get_suggestions'},mockContext(sample_get_suggestions)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('get_suggestions non-str', async()=>{ const r=await execute({action:'get_suggestions',email:123},mockContext(sample_get_suggestions)); assert.equal(r.metadata.success,false); });
});
describe('email-validator: timeout', ()=>{beforeEach(()=>{});
  it('to validate_email', async()=>{ const r=await execute({action:'validate_email',email:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to bulk_validate', async()=>{ const r=await execute({action:'bulk_validate',emails:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to check_domain', async()=>{ const r=await execute({action:'check_domain',domain:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_suggestions', async()=>{ const r=await execute({action:'get_suggestions',email:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('email-validator: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'validate_email',email:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'validate_email',email:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('email-validator: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('email-validator: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('email-validator: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('email-validator: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('validate_email req', ()=>{ assert.equal(validate({action:'validate_email'}).valid,false); assert.equal(validate({action:'validate_email',email:'t'}).valid,true); });
  it('bulk_validate req', ()=>{ assert.equal(validate({action:'bulk_validate'}).valid,false); assert.equal(validate({action:'bulk_validate',emails:'t'}).valid,true); });
  it('check_domain req', ()=>{ assert.equal(validate({action:'check_domain'}).valid,false); assert.equal(validate({action:'check_domain',domain:'t'}).valid,true); });
  it('get_suggestions req', ()=>{ assert.equal(validate({action:'get_suggestions'}).valid,false); assert.equal(validate({action:'get_suggestions',email:'t'}).valid,true); });
});
describe('email-validator: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'email-validator');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('email-validator: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_validate_email},config:{timeoutMs:5000}};const r=await execute({action:'validate_email',email:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('email-validator: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('email-validator: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['validate_email','bulk_validate','check_domain','get_suggestions']);});
});
describe('email-validator: paths', ()=>{beforeEach(()=>{});
  it('path validate_email', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_validate_email;}},config:{timeoutMs:5000}}; await execute({action:'validate_email',email:'test'},ctx); assert.ok(p!==null); });
  it('path bulk_validate', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_bulk_validate;}},config:{timeoutMs:5000}}; await execute({action:'bulk_validate',emails:'test'},ctx); assert.ok(p!==null); });
  it('path check_domain', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_check_domain;}},config:{timeoutMs:5000}}; await execute({action:'check_domain',domain:'test'},ctx); assert.ok(p!==null); });
  it('path get_suggestions', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_suggestions;}},config:{timeoutMs:5000}}; await execute({action:'get_suggestions',email:'test'},ctx); assert.ok(p!==null); });
});
