import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_search_logs = {"logs":[{"timestamp":"2024-01-01T00:00:00Z","level":"error","message":"Connection failed"}],"total":1};
const sample_get_stats = {"errorCount":5,"warnCount":20,"infoCount":500};
const sample_create_alert = {"alertId":"a1","pattern":"error","status":"active"};
const sample_list_alerts = {"alerts":[{"alertId":"a1","pattern":"error","triggered":false}]};
describe('log-monitor: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('log-monitor: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail search_logs', async()=>{ const r=await execute({action:'search_logs',query:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_stats', async()=>{ const r=await execute({action:'get_stats'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail create_alert', async()=>{ const r=await execute({action:'create_alert',pattern:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail list_alerts', async()=>{ const r=await execute({action:'list_alerts'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('log-monitor: search_logs', ()=>{beforeEach(()=>{});
  it('search_logs ok', async()=>{ const r=await execute({action:'search_logs',query:'test'},mockContext(sample_search_logs)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'search_logs'); });
  it('search_logs missing', async()=>{ const r=await execute({action:'search_logs'},mockContext(sample_search_logs)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('search_logs non-str', async()=>{ const r=await execute({action:'search_logs',query:123},mockContext(sample_search_logs)); assert.equal(r.metadata.success,false); });
});
describe('log-monitor: get_stats', ()=>{beforeEach(()=>{});
  it('get_stats ok', async()=>{ const r=await execute({action:'get_stats'},mockContext(sample_get_stats)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_stats'); });
});
describe('log-monitor: create_alert', ()=>{beforeEach(()=>{});
  it('create_alert ok', async()=>{ const r=await execute({action:'create_alert',pattern:'test'},mockContext(sample_create_alert)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'create_alert'); });
  it('create_alert missing', async()=>{ const r=await execute({action:'create_alert'},mockContext(sample_create_alert)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('create_alert non-str', async()=>{ const r=await execute({action:'create_alert',pattern:123},mockContext(sample_create_alert)); assert.equal(r.metadata.success,false); });
});
describe('log-monitor: list_alerts', ()=>{beforeEach(()=>{});
  it('list_alerts ok', async()=>{ const r=await execute({action:'list_alerts'},mockContext(sample_list_alerts)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'list_alerts'); });
});
describe('log-monitor: timeout', ()=>{beforeEach(()=>{});
  it('to search_logs', async()=>{ const r=await execute({action:'search_logs',query:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_stats', async()=>{ const r=await execute({action:'get_stats'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to create_alert', async()=>{ const r=await execute({action:'create_alert',pattern:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to list_alerts', async()=>{ const r=await execute({action:'list_alerts'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('log-monitor: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'search_logs',query:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'search_logs',query:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('log-monitor: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('log-monitor: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('log-monitor: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('log-monitor: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('search_logs req', ()=>{ assert.equal(validate({action:'search_logs'}).valid,false); assert.equal(validate({action:'search_logs',query:'t'}).valid,true); });
  it('get_stats ok', ()=>{ assert.equal(validate({action:'get_stats'}).valid,true); });
  it('create_alert req', ()=>{ assert.equal(validate({action:'create_alert'}).valid,false); assert.equal(validate({action:'create_alert',pattern:'t'}).valid,true); });
  it('list_alerts ok', ()=>{ assert.equal(validate({action:'list_alerts'}).valid,true); });
});
describe('log-monitor: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'log-monitor');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('log-monitor: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_search_logs},config:{timeoutMs:5000}};const r=await execute({action:'search_logs',query:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('log-monitor: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('log-monitor: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['search_logs','get_stats','create_alert','list_alerts']);});
});
describe('log-monitor: paths', ()=>{beforeEach(()=>{});
  it('path search_logs', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_search_logs;}},config:{timeoutMs:5000}}; await execute({action:'search_logs',query:'test'},ctx); assert.ok(p!==null); });
  it('path get_stats', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_stats;}},config:{timeoutMs:5000}}; await execute({action:'get_stats'},ctx); assert.ok(p!==null); });
  it('path create_alert', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_create_alert;}},config:{timeoutMs:5000}}; await execute({action:'create_alert',pattern:'test'},ctx); assert.ok(p!==null); });
  it('path list_alerts', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_list_alerts;}},config:{timeoutMs:5000}}; await execute({action:'list_alerts'},ctx); assert.ok(p!==null); });
});
