import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_search_questions = {"questions":[{"id":"q1","title":"What is AI?","followers":1000}]};
const sample_get_answers = {"answers":[{"id":"a1","content":"AI is...","upvotes":50}]};
const sample_post_answer = {"answerId":"a2","status":"published"};
const sample_get_trending = {"questions":[{"id":"q1","title":"Trending Q","views":50000}]};
describe('quora-zhihu-manager: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('quora-zhihu-manager: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail search_questions', async()=>{ const r=await execute({action:'search_questions',query:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_answers', async()=>{ const r=await execute({action:'get_answers',questionId:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail post_answer', async()=>{ const r=await execute({action:'post_answer',questionId:'test',content:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_trending', async()=>{ const r=await execute({action:'get_trending'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('quora-zhihu-manager: search_questions', ()=>{beforeEach(()=>{});
  it('search_questions ok', async()=>{ const r=await execute({action:'search_questions',query:'test'},mockContext(sample_search_questions)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'search_questions'); });
  it('search_questions missing', async()=>{ const r=await execute({action:'search_questions'},mockContext(sample_search_questions)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('search_questions non-str', async()=>{ const r=await execute({action:'search_questions',query:123},mockContext(sample_search_questions)); assert.equal(r.metadata.success,false); });
});
describe('quora-zhihu-manager: get_answers', ()=>{beforeEach(()=>{});
  it('get_answers ok', async()=>{ const r=await execute({action:'get_answers',questionId:'test'},mockContext(sample_get_answers)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_answers'); });
  it('get_answers missing', async()=>{ const r=await execute({action:'get_answers'},mockContext(sample_get_answers)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('get_answers non-str', async()=>{ const r=await execute({action:'get_answers',questionId:123},mockContext(sample_get_answers)); assert.equal(r.metadata.success,false); });
});
describe('quora-zhihu-manager: post_answer', ()=>{beforeEach(()=>{});
  it('post_answer ok', async()=>{ const r=await execute({action:'post_answer',questionId:'test',content:'test'},mockContext(sample_post_answer)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'post_answer'); });
  it('post_answer missing', async()=>{ const r=await execute({action:'post_answer'},mockContext(sample_post_answer)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('post_answer non-str', async()=>{ const r=await execute({action:'post_answer',questionId:123},mockContext(sample_post_answer)); assert.equal(r.metadata.success,false); });
});
describe('quora-zhihu-manager: get_trending', ()=>{beforeEach(()=>{});
  it('get_trending ok', async()=>{ const r=await execute({action:'get_trending'},mockContext(sample_get_trending)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_trending'); });
});
describe('quora-zhihu-manager: timeout', ()=>{beforeEach(()=>{});
  it('to search_questions', async()=>{ const r=await execute({action:'search_questions',query:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_answers', async()=>{ const r=await execute({action:'get_answers',questionId:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to post_answer', async()=>{ const r=await execute({action:'post_answer',questionId:'test',content:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_trending', async()=>{ const r=await execute({action:'get_trending'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('quora-zhihu-manager: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'search_questions',query:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'search_questions',query:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('quora-zhihu-manager: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('quora-zhihu-manager: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('quora-zhihu-manager: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('quora-zhihu-manager: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('search_questions req', ()=>{ assert.equal(validate({action:'search_questions'}).valid,false); assert.equal(validate({action:'search_questions',query:'t'}).valid,true); });
  it('get_answers req', ()=>{ assert.equal(validate({action:'get_answers'}).valid,false); assert.equal(validate({action:'get_answers',questionId:'t'}).valid,true); });
  it('post_answer req', ()=>{ assert.equal(validate({action:'post_answer'}).valid,false); assert.equal(validate({action:'post_answer',questionId:'t',content:'t'}).valid,true); });
  it('get_trending ok', ()=>{ assert.equal(validate({action:'get_trending'}).valid,true); });
});
describe('quora-zhihu-manager: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'quora-zhihu-manager');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('quora-zhihu-manager: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_search_questions},config:{timeoutMs:5000}};const r=await execute({action:'search_questions',query:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('quora-zhihu-manager: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('quora-zhihu-manager: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['search_questions','get_answers','post_answer','get_trending']);});
});
describe('quora-zhihu-manager: paths', ()=>{beforeEach(()=>{});
  it('path search_questions', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_search_questions;}},config:{timeoutMs:5000}}; await execute({action:'search_questions',query:'test'},ctx); assert.ok(p!==null); });
  it('path get_answers', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_answers;}},config:{timeoutMs:5000}}; await execute({action:'get_answers',questionId:'test'},ctx); assert.ok(p!==null); });
  it('path post_answer', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_post_answer;}},config:{timeoutMs:5000}}; await execute({action:'post_answer',questionId:'test',content:'test'},ctx); assert.ok(p!==null); });
  it('path get_trending', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_trending;}},config:{timeoutMs:5000}}; await execute({action:'get_trending'},ctx); assert.ok(p!==null); });
});
