import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_send_command = {"status":"executed","message":"Command sent"};
const sample_get_status = {"connected":true,"position":{"x":100,"y":64,"z":200},"health":20};
const sample_navigate_to = {"status":"navigating","eta":10};
const sample_get_inventory = {"items":[{"name":"diamond","count":5},{"name":"iron_ingot","count":32}]};
describe('minecraft-bot-controller: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('minecraft-bot-controller: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail send_command', async()=>{ const r=await execute({action:'send_command',command:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_status', async()=>{ const r=await execute({action:'get_status'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail navigate_to', async()=>{ const r=await execute({action:'navigate_to',x:'test',y:'test',z:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_inventory', async()=>{ const r=await execute({action:'get_inventory'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('minecraft-bot-controller: send_command', ()=>{beforeEach(()=>{});
  it('send_command ok', async()=>{ const r=await execute({action:'send_command',command:'test'},mockContext(sample_send_command)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'send_command'); });
  it('send_command missing', async()=>{ const r=await execute({action:'send_command'},mockContext(sample_send_command)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('send_command non-str', async()=>{ const r=await execute({action:'send_command',command:123},mockContext(sample_send_command)); assert.equal(r.metadata.success,false); });
});
describe('minecraft-bot-controller: get_status', ()=>{beforeEach(()=>{});
  it('get_status ok', async()=>{ const r=await execute({action:'get_status'},mockContext(sample_get_status)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_status'); });
});
describe('minecraft-bot-controller: navigate_to', ()=>{beforeEach(()=>{});
  it('navigate_to ok', async()=>{ const r=await execute({action:'navigate_to',x:'test',y:'test',z:'test'},mockContext(sample_navigate_to)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'navigate_to'); });
  it('navigate_to missing', async()=>{ const r=await execute({action:'navigate_to'},mockContext(sample_navigate_to)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('navigate_to non-str', async()=>{ const r=await execute({action:'navigate_to',x:123},mockContext(sample_navigate_to)); assert.equal(r.metadata.success,false); });
});
describe('minecraft-bot-controller: get_inventory', ()=>{beforeEach(()=>{});
  it('get_inventory ok', async()=>{ const r=await execute({action:'get_inventory'},mockContext(sample_get_inventory)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_inventory'); });
});
describe('minecraft-bot-controller: timeout', ()=>{beforeEach(()=>{});
  it('to send_command', async()=>{ const r=await execute({action:'send_command',command:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_status', async()=>{ const r=await execute({action:'get_status'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to navigate_to', async()=>{ const r=await execute({action:'navigate_to',x:'test',y:'test',z:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_inventory', async()=>{ const r=await execute({action:'get_inventory'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('minecraft-bot-controller: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'send_command',command:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'send_command',command:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('minecraft-bot-controller: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('minecraft-bot-controller: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('minecraft-bot-controller: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('minecraft-bot-controller: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('send_command req', ()=>{ assert.equal(validate({action:'send_command'}).valid,false); assert.equal(validate({action:'send_command',command:'t'}).valid,true); });
  it('get_status ok', ()=>{ assert.equal(validate({action:'get_status'}).valid,true); });
  it('navigate_to req', ()=>{ assert.equal(validate({action:'navigate_to'}).valid,false); assert.equal(validate({action:'navigate_to',x:'t',y:'t',z:'t'}).valid,true); });
  it('get_inventory ok', ()=>{ assert.equal(validate({action:'get_inventory'}).valid,true); });
});
describe('minecraft-bot-controller: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'minecraft-bot-controller');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('minecraft-bot-controller: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_send_command},config:{timeoutMs:5000}};const r=await execute({action:'send_command',command:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('minecraft-bot-controller: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('minecraft-bot-controller: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['send_command','get_status','navigate_to','get_inventory']);});
});
describe('minecraft-bot-controller: paths', ()=>{beforeEach(()=>{});
  it('path send_command', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_send_command;}},config:{timeoutMs:5000}}; await execute({action:'send_command',command:'test'},ctx); assert.ok(p!==null); });
  it('path get_status', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_status;}},config:{timeoutMs:5000}}; await execute({action:'get_status'},ctx); assert.ok(p!==null); });
  it('path navigate_to', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_navigate_to;}},config:{timeoutMs:5000}}; await execute({action:'navigate_to',x:'test',y:'test',z:'test'},ctx); assert.ok(p!==null); });
  it('path get_inventory', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_inventory;}},config:{timeoutMs:5000}}; await execute({action:'get_inventory'},ctx); assert.ok(p!==null); });
});
