import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_analyze_text = {"sentiment":"positive","score":0.85,"emotions":{"joy":0.7,"anger":0.05}};
const sample_analyze_batch = {"results":[{"text":"Great!","sentiment":"positive","score":0.9}],"avgScore":0.9};
const sample_detect_language = {"language":"en","confidence":0.99,"alternatives":[{"language":"de","confidence":0.01}]};
const sample_extract_entities = {"entities":[{"text":"Apple","type":"ORG","sentiment":"neutral"}]};
describe('sentiment-analysis: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('sentiment-analysis: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail analyze_text', async()=>{ const r=await execute({action:'analyze_text',text:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail analyze_batch', async()=>{ const r=await execute({action:'analyze_batch',texts:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail detect_language', async()=>{ const r=await execute({action:'detect_language',text:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail extract_entities', async()=>{ const r=await execute({action:'extract_entities',text:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('sentiment-analysis: analyze_text', ()=>{beforeEach(()=>{});
  it('analyze_text ok', async()=>{ const r=await execute({action:'analyze_text',text:'test'},mockContext(sample_analyze_text)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'analyze_text'); });
  it('analyze_text missing', async()=>{ const r=await execute({action:'analyze_text'},mockContext(sample_analyze_text)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('analyze_text non-str', async()=>{ const r=await execute({action:'analyze_text',text:123},mockContext(sample_analyze_text)); assert.equal(r.metadata.success,false); });
});
describe('sentiment-analysis: analyze_batch', ()=>{beforeEach(()=>{});
  it('analyze_batch ok', async()=>{ const r=await execute({action:'analyze_batch',texts:'test'},mockContext(sample_analyze_batch)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'analyze_batch'); });
  it('analyze_batch missing', async()=>{ const r=await execute({action:'analyze_batch'},mockContext(sample_analyze_batch)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('analyze_batch non-str', async()=>{ const r=await execute({action:'analyze_batch',texts:123},mockContext(sample_analyze_batch)); assert.equal(r.metadata.success,false); });
});
describe('sentiment-analysis: detect_language', ()=>{beforeEach(()=>{});
  it('detect_language ok', async()=>{ const r=await execute({action:'detect_language',text:'test'},mockContext(sample_detect_language)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'detect_language'); });
  it('detect_language missing', async()=>{ const r=await execute({action:'detect_language'},mockContext(sample_detect_language)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('detect_language non-str', async()=>{ const r=await execute({action:'detect_language',text:123},mockContext(sample_detect_language)); assert.equal(r.metadata.success,false); });
});
describe('sentiment-analysis: extract_entities', ()=>{beforeEach(()=>{});
  it('extract_entities ok', async()=>{ const r=await execute({action:'extract_entities',text:'test'},mockContext(sample_extract_entities)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'extract_entities'); });
  it('extract_entities missing', async()=>{ const r=await execute({action:'extract_entities'},mockContext(sample_extract_entities)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('extract_entities non-str', async()=>{ const r=await execute({action:'extract_entities',text:123},mockContext(sample_extract_entities)); assert.equal(r.metadata.success,false); });
});
describe('sentiment-analysis: timeout', ()=>{beforeEach(()=>{});
  it('to analyze_text', async()=>{ const r=await execute({action:'analyze_text',text:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to analyze_batch', async()=>{ const r=await execute({action:'analyze_batch',texts:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to detect_language', async()=>{ const r=await execute({action:'detect_language',text:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to extract_entities', async()=>{ const r=await execute({action:'extract_entities',text:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('sentiment-analysis: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'analyze_text',text:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'analyze_text',text:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('sentiment-analysis: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('sentiment-analysis: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('sentiment-analysis: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('sentiment-analysis: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('analyze_text req', ()=>{ assert.equal(validate({action:'analyze_text'}).valid,false); assert.equal(validate({action:'analyze_text',text:'t'}).valid,true); });
  it('analyze_batch req', ()=>{ assert.equal(validate({action:'analyze_batch'}).valid,false); assert.equal(validate({action:'analyze_batch',texts:'t'}).valid,true); });
  it('detect_language req', ()=>{ assert.equal(validate({action:'detect_language'}).valid,false); assert.equal(validate({action:'detect_language',text:'t'}).valid,true); });
  it('extract_entities req', ()=>{ assert.equal(validate({action:'extract_entities'}).valid,false); assert.equal(validate({action:'extract_entities',text:'t'}).valid,true); });
});
describe('sentiment-analysis: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'sentiment-analysis');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('sentiment-analysis: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_analyze_text},config:{timeoutMs:5000}};const r=await execute({action:'analyze_text',text:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('sentiment-analysis: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('sentiment-analysis: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['analyze_text','analyze_batch','detect_language','extract_entities']);});
});
describe('sentiment-analysis: paths', ()=>{beforeEach(()=>{});
  it('path analyze_text', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_analyze_text;}},config:{timeoutMs:5000}}; await execute({action:'analyze_text',text:'test'},ctx); assert.ok(p!==null); });
  it('path analyze_batch', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_analyze_batch;}},config:{timeoutMs:5000}}; await execute({action:'analyze_batch',texts:'test'},ctx); assert.ok(p!==null); });
  it('path detect_language', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_detect_language;}},config:{timeoutMs:5000}}; await execute({action:'detect_language',text:'test'},ctx); assert.ok(p!==null); });
  it('path extract_entities', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_extract_entities;}},config:{timeoutMs:5000}}; await execute({action:'extract_entities',text:'test'},ctx); assert.ok(p!==null); });
});
