import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_create_post = {"postId":"p1","platforms":["twitter","linkedin"],"status":"published"};
const sample_get_post = {"postId":"p1","content":"Hello","status":"published","metrics":{"likes":10}};
const sample_list_posts = {"posts":[{"postId":"p1","content":"Hello"}]};
const sample_delete_post = {"deleted":true};
describe('social-poster: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('social-poster: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail create_post', async()=>{ const r=await execute({action:'create_post',content:'test',platforms:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_post', async()=>{ const r=await execute({action:'get_post',postId:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail list_posts', async()=>{ const r=await execute({action:'list_posts'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail delete_post', async()=>{ const r=await execute({action:'delete_post',postId:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('social-poster: create_post', ()=>{beforeEach(()=>{});
  it('create_post ok', async()=>{ const r=await execute({action:'create_post',content:'test',platforms:'test'},mockContext(sample_create_post)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'create_post'); });
  it('create_post missing', async()=>{ const r=await execute({action:'create_post'},mockContext(sample_create_post)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('create_post non-str', async()=>{ const r=await execute({action:'create_post',content:123},mockContext(sample_create_post)); assert.equal(r.metadata.success,false); });
});
describe('social-poster: get_post', ()=>{beforeEach(()=>{});
  it('get_post ok', async()=>{ const r=await execute({action:'get_post',postId:'test'},mockContext(sample_get_post)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_post'); });
  it('get_post missing', async()=>{ const r=await execute({action:'get_post'},mockContext(sample_get_post)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('get_post non-str', async()=>{ const r=await execute({action:'get_post',postId:123},mockContext(sample_get_post)); assert.equal(r.metadata.success,false); });
});
describe('social-poster: list_posts', ()=>{beforeEach(()=>{});
  it('list_posts ok', async()=>{ const r=await execute({action:'list_posts'},mockContext(sample_list_posts)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'list_posts'); });
});
describe('social-poster: delete_post', ()=>{beforeEach(()=>{});
  it('delete_post ok', async()=>{ const r=await execute({action:'delete_post',postId:'test'},mockContext(sample_delete_post)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'delete_post'); });
  it('delete_post missing', async()=>{ const r=await execute({action:'delete_post'},mockContext(sample_delete_post)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('delete_post non-str', async()=>{ const r=await execute({action:'delete_post',postId:123},mockContext(sample_delete_post)); assert.equal(r.metadata.success,false); });
});
describe('social-poster: timeout', ()=>{beforeEach(()=>{});
  it('to create_post', async()=>{ const r=await execute({action:'create_post',content:'test',platforms:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_post', async()=>{ const r=await execute({action:'get_post',postId:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to list_posts', async()=>{ const r=await execute({action:'list_posts'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to delete_post', async()=>{ const r=await execute({action:'delete_post',postId:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('social-poster: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'create_post',content:'test',platforms:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'create_post',content:'test',platforms:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('social-poster: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('social-poster: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('social-poster: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('social-poster: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('create_post req', ()=>{ assert.equal(validate({action:'create_post'}).valid,false); assert.equal(validate({action:'create_post',content:'t',platforms:'t'}).valid,true); });
  it('get_post req', ()=>{ assert.equal(validate({action:'get_post'}).valid,false); assert.equal(validate({action:'get_post',postId:'t'}).valid,true); });
  it('list_posts ok', ()=>{ assert.equal(validate({action:'list_posts'}).valid,true); });
  it('delete_post req', ()=>{ assert.equal(validate({action:'delete_post'}).valid,false); assert.equal(validate({action:'delete_post',postId:'t'}).valid,true); });
});
describe('social-poster: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'social-poster');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('social-poster: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_create_post},config:{timeoutMs:5000}};const r=await execute({action:'create_post',content:'test',platforms:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('social-poster: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('social-poster: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['create_post','get_post','list_posts','delete_post']);});
});
describe('social-poster: paths', ()=>{beforeEach(()=>{});
  it('path create_post', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_create_post;}},config:{timeoutMs:5000}}; await execute({action:'create_post',content:'test',platforms:'test'},ctx); assert.ok(p!==null); });
  it('path get_post', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_post;}},config:{timeoutMs:5000}}; await execute({action:'get_post',postId:'test'},ctx); assert.ok(p!==null); });
  it('path list_posts', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_list_posts;}},config:{timeoutMs:5000}}; await execute({action:'list_posts'},ctx); assert.ok(p!==null); });
  it('path delete_post', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_delete_post;}},config:{timeoutMs:5000}}; await execute({action:'delete_post',postId:'test'},ctx); assert.ok(p!==null); });
});
