import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_analyze_query = {"complexity":"medium","suggestions":["Add index on column_a"],"estimatedCost":150};
const sample_explain_query = {"plan":{"type":"Seq Scan","cost":100,"rows":1000},"explanation":"Full table scan on users table"};
const sample_format_query = {"formatted":"SELECT\n  id\nFROM users\nWHERE active = true;"};
const sample_validate_query = {"valid":true,"errors":[],"warnings":["Missing WHERE clause"]};
describe('sql-analyzer: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('sql-analyzer: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail analyze_query', async()=>{ const r=await execute({action:'analyze_query',query:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail explain_query', async()=>{ const r=await execute({action:'explain_query',query:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail format_query', async()=>{ const r=await execute({action:'format_query',query:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail validate_query', async()=>{ const r=await execute({action:'validate_query',query:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('sql-analyzer: analyze_query', ()=>{beforeEach(()=>{});
  it('analyze_query ok', async()=>{ const r=await execute({action:'analyze_query',query:'test'},mockContext(sample_analyze_query)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'analyze_query'); });
  it('analyze_query missing', async()=>{ const r=await execute({action:'analyze_query'},mockContext(sample_analyze_query)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('analyze_query non-str', async()=>{ const r=await execute({action:'analyze_query',query:123},mockContext(sample_analyze_query)); assert.equal(r.metadata.success,false); });
});
describe('sql-analyzer: explain_query', ()=>{beforeEach(()=>{});
  it('explain_query ok', async()=>{ const r=await execute({action:'explain_query',query:'test'},mockContext(sample_explain_query)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'explain_query'); });
  it('explain_query missing', async()=>{ const r=await execute({action:'explain_query'},mockContext(sample_explain_query)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('explain_query non-str', async()=>{ const r=await execute({action:'explain_query',query:123},mockContext(sample_explain_query)); assert.equal(r.metadata.success,false); });
});
describe('sql-analyzer: format_query', ()=>{beforeEach(()=>{});
  it('format_query ok', async()=>{ const r=await execute({action:'format_query',query:'test'},mockContext(sample_format_query)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'format_query'); });
  it('format_query missing', async()=>{ const r=await execute({action:'format_query'},mockContext(sample_format_query)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('format_query non-str', async()=>{ const r=await execute({action:'format_query',query:123},mockContext(sample_format_query)); assert.equal(r.metadata.success,false); });
});
describe('sql-analyzer: validate_query', ()=>{beforeEach(()=>{});
  it('validate_query ok', async()=>{ const r=await execute({action:'validate_query',query:'test'},mockContext(sample_validate_query)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'validate_query'); });
  it('validate_query missing', async()=>{ const r=await execute({action:'validate_query'},mockContext(sample_validate_query)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('validate_query non-str', async()=>{ const r=await execute({action:'validate_query',query:123},mockContext(sample_validate_query)); assert.equal(r.metadata.success,false); });
});
describe('sql-analyzer: timeout', ()=>{beforeEach(()=>{});
  it('to analyze_query', async()=>{ const r=await execute({action:'analyze_query',query:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to explain_query', async()=>{ const r=await execute({action:'explain_query',query:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to format_query', async()=>{ const r=await execute({action:'format_query',query:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to validate_query', async()=>{ const r=await execute({action:'validate_query',query:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('sql-analyzer: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'analyze_query',query:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'analyze_query',query:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('sql-analyzer: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('sql-analyzer: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('sql-analyzer: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('sql-analyzer: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('analyze_query req', ()=>{ assert.equal(validate({action:'analyze_query'}).valid,false); assert.equal(validate({action:'analyze_query',query:'t'}).valid,true); });
  it('explain_query req', ()=>{ assert.equal(validate({action:'explain_query'}).valid,false); assert.equal(validate({action:'explain_query',query:'t'}).valid,true); });
  it('format_query req', ()=>{ assert.equal(validate({action:'format_query'}).valid,false); assert.equal(validate({action:'format_query',query:'t'}).valid,true); });
  it('validate_query req', ()=>{ assert.equal(validate({action:'validate_query'}).valid,false); assert.equal(validate({action:'validate_query',query:'t'}).valid,true); });
});
describe('sql-analyzer: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'sql-analyzer');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('sql-analyzer: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_analyze_query},config:{timeoutMs:5000}};const r=await execute({action:'analyze_query',query:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('sql-analyzer: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('sql-analyzer: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['analyze_query','explain_query','format_query','validate_query']);});
});
describe('sql-analyzer: paths', ()=>{beforeEach(()=>{});
  it('path analyze_query', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_analyze_query;}},config:{timeoutMs:5000}}; await execute({action:'analyze_query',query:'test'},ctx); assert.ok(p!==null); });
  it('path explain_query', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_explain_query;}},config:{timeoutMs:5000}}; await execute({action:'explain_query',query:'test'},ctx); assert.ok(p!==null); });
  it('path format_query', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_format_query;}},config:{timeoutMs:5000}}; await execute({action:'format_query',query:'test'},ctx); assert.ok(p!==null); });
  it('path validate_query', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_validate_query;}},config:{timeoutMs:5000}}; await execute({action:'validate_query',query:'test'},ctx); assert.ok(p!==null); });
});
