import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_create_sandbox = {"sandboxId":"sb1","status":"running"};
const sample_exec_code = {"stdout":"Hello","stderr":"","exitCode":0};
const sample_upload_file = {"path":"/home/user/file.py"};
const sample_close_sandbox = {"status":"closed"};
describe('code-sandbox-e2b: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('code-sandbox-e2b: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail create_sandbox', async()=>{ const r=await execute({action:'create_sandbox'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail exec_code', async()=>{ const r=await execute({action:'exec_code',sandboxId:'test',code:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail upload_file', async()=>{ const r=await execute({action:'upload_file',sandboxId:'test',path:'test',content:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail close_sandbox', async()=>{ const r=await execute({action:'close_sandbox',sandboxId:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('code-sandbox-e2b: create_sandbox', ()=>{beforeEach(()=>{});
  it('create_sandbox ok', async()=>{ const r=await execute({action:'create_sandbox'},mockContext(sample_create_sandbox)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'create_sandbox'); });
});
describe('code-sandbox-e2b: exec_code', ()=>{beforeEach(()=>{});
  it('exec_code ok', async()=>{ const r=await execute({action:'exec_code',sandboxId:'test',code:'test'},mockContext(sample_exec_code)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'exec_code'); });
  it('exec_code missing', async()=>{ const r=await execute({action:'exec_code'},mockContext(sample_exec_code)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('exec_code non-str', async()=>{ const r=await execute({action:'exec_code',sandboxId:123},mockContext(sample_exec_code)); assert.equal(r.metadata.success,false); });
});
describe('code-sandbox-e2b: upload_file', ()=>{beforeEach(()=>{});
  it('upload_file ok', async()=>{ const r=await execute({action:'upload_file',sandboxId:'test',path:'test',content:'test'},mockContext(sample_upload_file)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'upload_file'); });
  it('upload_file missing', async()=>{ const r=await execute({action:'upload_file'},mockContext(sample_upload_file)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('upload_file non-str', async()=>{ const r=await execute({action:'upload_file',sandboxId:123},mockContext(sample_upload_file)); assert.equal(r.metadata.success,false); });
});
describe('code-sandbox-e2b: close_sandbox', ()=>{beforeEach(()=>{});
  it('close_sandbox ok', async()=>{ const r=await execute({action:'close_sandbox',sandboxId:'test'},mockContext(sample_close_sandbox)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'close_sandbox'); });
  it('close_sandbox missing', async()=>{ const r=await execute({action:'close_sandbox'},mockContext(sample_close_sandbox)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('close_sandbox non-str', async()=>{ const r=await execute({action:'close_sandbox',sandboxId:123},mockContext(sample_close_sandbox)); assert.equal(r.metadata.success,false); });
});
describe('code-sandbox-e2b: timeout', ()=>{beforeEach(()=>{});
  it('to create_sandbox', async()=>{ const r=await execute({action:'create_sandbox'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to exec_code', async()=>{ const r=await execute({action:'exec_code',sandboxId:'test',code:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to upload_file', async()=>{ const r=await execute({action:'upload_file',sandboxId:'test',path:'test',content:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to close_sandbox', async()=>{ const r=await execute({action:'close_sandbox',sandboxId:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('code-sandbox-e2b: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'create_sandbox'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'create_sandbox'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('code-sandbox-e2b: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('code-sandbox-e2b: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('code-sandbox-e2b: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('code-sandbox-e2b: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('create_sandbox ok', ()=>{ assert.equal(validate({action:'create_sandbox'}).valid,true); });
  it('exec_code req', ()=>{ assert.equal(validate({action:'exec_code'}).valid,false); assert.equal(validate({action:'exec_code',sandboxId:'t',code:'t'}).valid,true); });
  it('upload_file req', ()=>{ assert.equal(validate({action:'upload_file'}).valid,false); assert.equal(validate({action:'upload_file',sandboxId:'t',path:'t',content:'t'}).valid,true); });
  it('close_sandbox req', ()=>{ assert.equal(validate({action:'close_sandbox'}).valid,false); assert.equal(validate({action:'close_sandbox',sandboxId:'t'}).valid,true); });
});
describe('code-sandbox-e2b: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'code-sandbox-e2b');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('code-sandbox-e2b: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_create_sandbox},config:{timeoutMs:5000}};const r=await execute({action:'create_sandbox'},ctx);assert.equal(r.metadata.success,true);});
});
describe('code-sandbox-e2b: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('code-sandbox-e2b: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['create_sandbox','exec_code','upload_file','close_sandbox']);});
});
describe('code-sandbox-e2b: paths', ()=>{beforeEach(()=>{});
  it('path create_sandbox', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_create_sandbox;}},config:{timeoutMs:5000}}; await execute({action:'create_sandbox'},ctx); assert.ok(p!==null); });
  it('path exec_code', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_exec_code;}},config:{timeoutMs:5000}}; await execute({action:'exec_code',sandboxId:'test',code:'test'},ctx); assert.ok(p!==null); });
  it('path upload_file', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_upload_file;}},config:{timeoutMs:5000}}; await execute({action:'upload_file',sandboxId:'test',path:'test',content:'test'},ctx); assert.ok(p!==null); });
  it('path close_sandbox', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_close_sandbox;}},config:{timeoutMs:5000}}; await execute({action:'close_sandbox',sandboxId:'test'},ctx); assert.ok(p!==null); });
});
