import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_get_info = {"title":"Video Title","duration":300,"formats":[{"quality":"720p","size":50000000}]};
const sample_download = {"taskId":"dl1","status":"downloading","progress":0};
const sample_get_status = {"taskId":"dl1","status":"completed","outputPath":"/downloads/video.mp4"};
const sample_extract_audio = {"taskId":"ea1","status":"processing"};
describe('video-downloader: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('video-downloader: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail get_info', async()=>{ const r=await execute({action:'get_info',url:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail download', async()=>{ const r=await execute({action:'download',url:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_status', async()=>{ const r=await execute({action:'get_status',taskId:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail extract_audio', async()=>{ const r=await execute({action:'extract_audio',url:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('video-downloader: get_info', ()=>{beforeEach(()=>{});
  it('get_info ok', async()=>{ const r=await execute({action:'get_info',url:'test'},mockContext(sample_get_info)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_info'); });
  it('get_info missing', async()=>{ const r=await execute({action:'get_info'},mockContext(sample_get_info)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('get_info non-str', async()=>{ const r=await execute({action:'get_info',url:123},mockContext(sample_get_info)); assert.equal(r.metadata.success,false); });
});
describe('video-downloader: download', ()=>{beforeEach(()=>{});
  it('download ok', async()=>{ const r=await execute({action:'download',url:'test'},mockContext(sample_download)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'download'); });
  it('download missing', async()=>{ const r=await execute({action:'download'},mockContext(sample_download)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('download non-str', async()=>{ const r=await execute({action:'download',url:123},mockContext(sample_download)); assert.equal(r.metadata.success,false); });
});
describe('video-downloader: get_status', ()=>{beforeEach(()=>{});
  it('get_status ok', async()=>{ const r=await execute({action:'get_status',taskId:'test'},mockContext(sample_get_status)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_status'); });
  it('get_status missing', async()=>{ const r=await execute({action:'get_status'},mockContext(sample_get_status)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('get_status non-str', async()=>{ const r=await execute({action:'get_status',taskId:123},mockContext(sample_get_status)); assert.equal(r.metadata.success,false); });
});
describe('video-downloader: extract_audio', ()=>{beforeEach(()=>{});
  it('extract_audio ok', async()=>{ const r=await execute({action:'extract_audio',url:'test'},mockContext(sample_extract_audio)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'extract_audio'); });
  it('extract_audio missing', async()=>{ const r=await execute({action:'extract_audio'},mockContext(sample_extract_audio)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('extract_audio non-str', async()=>{ const r=await execute({action:'extract_audio',url:123},mockContext(sample_extract_audio)); assert.equal(r.metadata.success,false); });
});
describe('video-downloader: timeout', ()=>{beforeEach(()=>{});
  it('to get_info', async()=>{ const r=await execute({action:'get_info',url:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to download', async()=>{ const r=await execute({action:'download',url:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_status', async()=>{ const r=await execute({action:'get_status',taskId:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to extract_audio', async()=>{ const r=await execute({action:'extract_audio',url:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('video-downloader: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'get_info',url:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'get_info',url:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('video-downloader: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('video-downloader: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('video-downloader: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('video-downloader: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('get_info req', ()=>{ assert.equal(validate({action:'get_info'}).valid,false); assert.equal(validate({action:'get_info',url:'t'}).valid,true); });
  it('download req', ()=>{ assert.equal(validate({action:'download'}).valid,false); assert.equal(validate({action:'download',url:'t'}).valid,true); });
  it('get_status req', ()=>{ assert.equal(validate({action:'get_status'}).valid,false); assert.equal(validate({action:'get_status',taskId:'t'}).valid,true); });
  it('extract_audio req', ()=>{ assert.equal(validate({action:'extract_audio'}).valid,false); assert.equal(validate({action:'extract_audio',url:'t'}).valid,true); });
});
describe('video-downloader: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'video-downloader');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('video-downloader: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_get_info},config:{timeoutMs:5000}};const r=await execute({action:'get_info',url:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('video-downloader: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('video-downloader: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['get_info','download','get_status','extract_audio']);});
});
describe('video-downloader: paths', ()=>{beforeEach(()=>{});
  it('path get_info', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_info;}},config:{timeoutMs:5000}}; await execute({action:'get_info',url:'test'},ctx); assert.ok(p!==null); });
  it('path download', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_download;}},config:{timeoutMs:5000}}; await execute({action:'download',url:'test'},ctx); assert.ok(p!==null); });
  it('path get_status', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_status;}},config:{timeoutMs:5000}}; await execute({action:'get_status',taskId:'test'},ctx); assert.ok(p!==null); });
  it('path extract_audio', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_extract_audio;}},config:{timeoutMs:5000}}; await execute({action:'extract_audio',url:'test'},ctx); assert.ok(p!==null); });
});
