import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_parse_export = {"recordCount":5000,"dateRange":{"start":"2023-01-01","end":"2024-01-01"}};
const sample_get_summary = {"steps":{"avg":8500,"total":3102500},"heartRate":{"avg":72,"min":55,"max":150}};
const sample_get_workouts = {"workouts":[{"type":"Running","duration":1800,"calories":300,"date":"2024-01-01"}]};
const sample_export_csv = {"outputPath":"/output/steps.csv","rows":365};
describe('apple-health-parser: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('apple-health-parser: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail parse_export', async()=>{ const r=await execute({action:'parse_export',filePath:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_summary', async()=>{ const r=await execute({action:'get_summary',filePath:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_workouts', async()=>{ const r=await execute({action:'get_workouts',filePath:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail export_csv', async()=>{ const r=await execute({action:'export_csv',filePath:'test',metric:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('apple-health-parser: parse_export', ()=>{beforeEach(()=>{});
  it('parse_export ok', async()=>{ const r=await execute({action:'parse_export',filePath:'test'},mockContext(sample_parse_export)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'parse_export'); });
  it('parse_export missing', async()=>{ const r=await execute({action:'parse_export'},mockContext(sample_parse_export)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('parse_export non-str', async()=>{ const r=await execute({action:'parse_export',filePath:123},mockContext(sample_parse_export)); assert.equal(r.metadata.success,false); });
});
describe('apple-health-parser: get_summary', ()=>{beforeEach(()=>{});
  it('get_summary ok', async()=>{ const r=await execute({action:'get_summary',filePath:'test'},mockContext(sample_get_summary)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_summary'); });
  it('get_summary missing', async()=>{ const r=await execute({action:'get_summary'},mockContext(sample_get_summary)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('get_summary non-str', async()=>{ const r=await execute({action:'get_summary',filePath:123},mockContext(sample_get_summary)); assert.equal(r.metadata.success,false); });
});
describe('apple-health-parser: get_workouts', ()=>{beforeEach(()=>{});
  it('get_workouts ok', async()=>{ const r=await execute({action:'get_workouts',filePath:'test'},mockContext(sample_get_workouts)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_workouts'); });
  it('get_workouts missing', async()=>{ const r=await execute({action:'get_workouts'},mockContext(sample_get_workouts)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('get_workouts non-str', async()=>{ const r=await execute({action:'get_workouts',filePath:123},mockContext(sample_get_workouts)); assert.equal(r.metadata.success,false); });
});
describe('apple-health-parser: export_csv', ()=>{beforeEach(()=>{});
  it('export_csv ok', async()=>{ const r=await execute({action:'export_csv',filePath:'test',metric:'test'},mockContext(sample_export_csv)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'export_csv'); });
  it('export_csv missing', async()=>{ const r=await execute({action:'export_csv'},mockContext(sample_export_csv)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('export_csv non-str', async()=>{ const r=await execute({action:'export_csv',filePath:123},mockContext(sample_export_csv)); assert.equal(r.metadata.success,false); });
});
describe('apple-health-parser: timeout', ()=>{beforeEach(()=>{});
  it('to parse_export', async()=>{ const r=await execute({action:'parse_export',filePath:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_summary', async()=>{ const r=await execute({action:'get_summary',filePath:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_workouts', async()=>{ const r=await execute({action:'get_workouts',filePath:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to export_csv', async()=>{ const r=await execute({action:'export_csv',filePath:'test',metric:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('apple-health-parser: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'parse_export',filePath:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'parse_export',filePath:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('apple-health-parser: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('apple-health-parser: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('apple-health-parser: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('apple-health-parser: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('parse_export req', ()=>{ assert.equal(validate({action:'parse_export'}).valid,false); assert.equal(validate({action:'parse_export',filePath:'t'}).valid,true); });
  it('get_summary req', ()=>{ assert.equal(validate({action:'get_summary'}).valid,false); assert.equal(validate({action:'get_summary',filePath:'t'}).valid,true); });
  it('get_workouts req', ()=>{ assert.equal(validate({action:'get_workouts'}).valid,false); assert.equal(validate({action:'get_workouts',filePath:'t'}).valid,true); });
  it('export_csv req', ()=>{ assert.equal(validate({action:'export_csv'}).valid,false); assert.equal(validate({action:'export_csv',filePath:'t',metric:'t'}).valid,true); });
});
describe('apple-health-parser: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'apple-health-parser');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('apple-health-parser: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_parse_export},config:{timeoutMs:5000}};const r=await execute({action:'parse_export',filePath:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('apple-health-parser: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('apple-health-parser: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['parse_export','get_summary','get_workouts','export_csv']);});
});
describe('apple-health-parser: paths', ()=>{beforeEach(()=>{});
  it('path parse_export', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_parse_export;}},config:{timeoutMs:5000}}; await execute({action:'parse_export',filePath:'test'},ctx); assert.ok(p!==null); });
  it('path get_summary', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_summary;}},config:{timeoutMs:5000}}; await execute({action:'get_summary',filePath:'test'},ctx); assert.ok(p!==null); });
  it('path get_workouts', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_workouts;}},config:{timeoutMs:5000}}; await execute({action:'get_workouts',filePath:'test'},ctx); assert.ok(p!==null); });
  it('path export_csv', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_export_csv;}},config:{timeoutMs:5000}}; await execute({action:'export_csv',filePath:'test',metric:'test'},ctx); assert.ok(p!==null); });
});
