import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_generate_prompt = {"prompt":"Generated prompt text","tokens":150};
const sample_optimize_prompt = {"optimized":"Better prompt","improvements":["clarity","specificity"]};
const sample_list_templates = {"templates":[{"id":"t1","name":"Code Review","category":"engineering"}]};
const sample_evaluate_prompt = {"score":85,"feedback":["Good specificity","Add constraints"]};
describe('prompt-generator: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('prompt-generator: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail generate_prompt', async()=>{ const r=await execute({action:'generate_prompt',task:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail optimize_prompt', async()=>{ const r=await execute({action:'optimize_prompt',prompt:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail list_templates', async()=>{ const r=await execute({action:'list_templates'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail evaluate_prompt', async()=>{ const r=await execute({action:'evaluate_prompt',prompt:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('prompt-generator: generate_prompt', ()=>{beforeEach(()=>{});
  it('generate_prompt ok', async()=>{ const r=await execute({action:'generate_prompt',task:'test'},mockContext(sample_generate_prompt)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'generate_prompt'); });
  it('generate_prompt missing', async()=>{ const r=await execute({action:'generate_prompt'},mockContext(sample_generate_prompt)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('generate_prompt non-str', async()=>{ const r=await execute({action:'generate_prompt',task:123},mockContext(sample_generate_prompt)); assert.equal(r.metadata.success,false); });
});
describe('prompt-generator: optimize_prompt', ()=>{beforeEach(()=>{});
  it('optimize_prompt ok', async()=>{ const r=await execute({action:'optimize_prompt',prompt:'test'},mockContext(sample_optimize_prompt)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'optimize_prompt'); });
  it('optimize_prompt missing', async()=>{ const r=await execute({action:'optimize_prompt'},mockContext(sample_optimize_prompt)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('optimize_prompt non-str', async()=>{ const r=await execute({action:'optimize_prompt',prompt:123},mockContext(sample_optimize_prompt)); assert.equal(r.metadata.success,false); });
});
describe('prompt-generator: list_templates', ()=>{beforeEach(()=>{});
  it('list_templates ok', async()=>{ const r=await execute({action:'list_templates'},mockContext(sample_list_templates)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'list_templates'); });
});
describe('prompt-generator: evaluate_prompt', ()=>{beforeEach(()=>{});
  it('evaluate_prompt ok', async()=>{ const r=await execute({action:'evaluate_prompt',prompt:'test'},mockContext(sample_evaluate_prompt)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'evaluate_prompt'); });
  it('evaluate_prompt missing', async()=>{ const r=await execute({action:'evaluate_prompt'},mockContext(sample_evaluate_prompt)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('evaluate_prompt non-str', async()=>{ const r=await execute({action:'evaluate_prompt',prompt:123},mockContext(sample_evaluate_prompt)); assert.equal(r.metadata.success,false); });
});
describe('prompt-generator: timeout', ()=>{beforeEach(()=>{});
  it('to generate_prompt', async()=>{ const r=await execute({action:'generate_prompt',task:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to optimize_prompt', async()=>{ const r=await execute({action:'optimize_prompt',prompt:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to list_templates', async()=>{ const r=await execute({action:'list_templates'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to evaluate_prompt', async()=>{ const r=await execute({action:'evaluate_prompt',prompt:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('prompt-generator: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'generate_prompt',task:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'generate_prompt',task:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('prompt-generator: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('prompt-generator: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('prompt-generator: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('prompt-generator: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('generate_prompt req', ()=>{ assert.equal(validate({action:'generate_prompt'}).valid,false); assert.equal(validate({action:'generate_prompt',task:'t'}).valid,true); });
  it('optimize_prompt req', ()=>{ assert.equal(validate({action:'optimize_prompt'}).valid,false); assert.equal(validate({action:'optimize_prompt',prompt:'t'}).valid,true); });
  it('list_templates ok', ()=>{ assert.equal(validate({action:'list_templates'}).valid,true); });
  it('evaluate_prompt req', ()=>{ assert.equal(validate({action:'evaluate_prompt'}).valid,false); assert.equal(validate({action:'evaluate_prompt',prompt:'t'}).valid,true); });
});
describe('prompt-generator: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'prompt-generator');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('prompt-generator: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_generate_prompt},config:{timeoutMs:5000}};const r=await execute({action:'generate_prompt',task:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('prompt-generator: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('prompt-generator: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['generate_prompt','optimize_prompt','list_templates','evaluate_prompt']);});
});
describe('prompt-generator: paths', ()=>{beforeEach(()=>{});
  it('path generate_prompt', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_generate_prompt;}},config:{timeoutMs:5000}}; await execute({action:'generate_prompt',task:'test'},ctx); assert.ok(p!==null); });
  it('path optimize_prompt', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_optimize_prompt;}},config:{timeoutMs:5000}}; await execute({action:'optimize_prompt',prompt:'test'},ctx); assert.ok(p!==null); });
  it('path list_templates', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_list_templates;}},config:{timeoutMs:5000}}; await execute({action:'list_templates'},ctx); assert.ok(p!==null); });
  it('path evaluate_prompt', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_evaluate_prompt;}},config:{timeoutMs:5000}}; await execute({action:'evaluate_prompt',prompt:'test'},ctx); assert.ok(p!==null); });
});
