import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_generate_tests = {"tests":"test code here","testCount":5,"coverage":85};
const sample_analyze_coverage = {"coverage":78,"uncoveredLines":[10,15,22]};
const sample_suggest_cases = {"cases":[{"description":"edge case: empty input","priority":"high"}]};
const sample_validate_tests = {"valid":true,"issues":[],"assertions":12};
describe('test-generator: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('test-generator: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail generate_tests', async()=>{ const r=await execute({action:'generate_tests',code:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail analyze_coverage', async()=>{ const r=await execute({action:'analyze_coverage',code:'test',tests:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail suggest_cases', async()=>{ const r=await execute({action:'suggest_cases',code:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail validate_tests', async()=>{ const r=await execute({action:'validate_tests',tests:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('test-generator: generate_tests', ()=>{beforeEach(()=>{});
  it('generate_tests ok', async()=>{ const r=await execute({action:'generate_tests',code:'test'},mockContext(sample_generate_tests)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'generate_tests'); });
  it('generate_tests missing', async()=>{ const r=await execute({action:'generate_tests'},mockContext(sample_generate_tests)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('generate_tests non-str', async()=>{ const r=await execute({action:'generate_tests',code:123},mockContext(sample_generate_tests)); assert.equal(r.metadata.success,false); });
});
describe('test-generator: analyze_coverage', ()=>{beforeEach(()=>{});
  it('analyze_coverage ok', async()=>{ const r=await execute({action:'analyze_coverage',code:'test',tests:'test'},mockContext(sample_analyze_coverage)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'analyze_coverage'); });
  it('analyze_coverage missing', async()=>{ const r=await execute({action:'analyze_coverage'},mockContext(sample_analyze_coverage)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('analyze_coverage non-str', async()=>{ const r=await execute({action:'analyze_coverage',code:123},mockContext(sample_analyze_coverage)); assert.equal(r.metadata.success,false); });
});
describe('test-generator: suggest_cases', ()=>{beforeEach(()=>{});
  it('suggest_cases ok', async()=>{ const r=await execute({action:'suggest_cases',code:'test'},mockContext(sample_suggest_cases)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'suggest_cases'); });
  it('suggest_cases missing', async()=>{ const r=await execute({action:'suggest_cases'},mockContext(sample_suggest_cases)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('suggest_cases non-str', async()=>{ const r=await execute({action:'suggest_cases',code:123},mockContext(sample_suggest_cases)); assert.equal(r.metadata.success,false); });
});
describe('test-generator: validate_tests', ()=>{beforeEach(()=>{});
  it('validate_tests ok', async()=>{ const r=await execute({action:'validate_tests',tests:'test'},mockContext(sample_validate_tests)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'validate_tests'); });
  it('validate_tests missing', async()=>{ const r=await execute({action:'validate_tests'},mockContext(sample_validate_tests)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('validate_tests non-str', async()=>{ const r=await execute({action:'validate_tests',tests:123},mockContext(sample_validate_tests)); assert.equal(r.metadata.success,false); });
});
describe('test-generator: timeout', ()=>{beforeEach(()=>{});
  it('to generate_tests', async()=>{ const r=await execute({action:'generate_tests',code:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to analyze_coverage', async()=>{ const r=await execute({action:'analyze_coverage',code:'test',tests:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to suggest_cases', async()=>{ const r=await execute({action:'suggest_cases',code:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to validate_tests', async()=>{ const r=await execute({action:'validate_tests',tests:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('test-generator: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'generate_tests',code:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'generate_tests',code:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('test-generator: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('test-generator: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('test-generator: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('test-generator: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('generate_tests req', ()=>{ assert.equal(validate({action:'generate_tests'}).valid,false); assert.equal(validate({action:'generate_tests',code:'t'}).valid,true); });
  it('analyze_coverage req', ()=>{ assert.equal(validate({action:'analyze_coverage'}).valid,false); assert.equal(validate({action:'analyze_coverage',code:'t',tests:'t'}).valid,true); });
  it('suggest_cases req', ()=>{ assert.equal(validate({action:'suggest_cases'}).valid,false); assert.equal(validate({action:'suggest_cases',code:'t'}).valid,true); });
  it('validate_tests req', ()=>{ assert.equal(validate({action:'validate_tests'}).valid,false); assert.equal(validate({action:'validate_tests',tests:'t'}).valid,true); });
});
describe('test-generator: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'test-generator');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('test-generator: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_generate_tests},config:{timeoutMs:5000}};const r=await execute({action:'generate_tests',code:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('test-generator: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('test-generator: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['generate_tests','analyze_coverage','suggest_cases','validate_tests']);});
});
describe('test-generator: paths', ()=>{beforeEach(()=>{});
  it('path generate_tests', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_generate_tests;}},config:{timeoutMs:5000}}; await execute({action:'generate_tests',code:'test'},ctx); assert.ok(p!==null); });
  it('path analyze_coverage', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_analyze_coverage;}},config:{timeoutMs:5000}}; await execute({action:'analyze_coverage',code:'test',tests:'test'},ctx); assert.ok(p!==null); });
  it('path suggest_cases', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_suggest_cases;}},config:{timeoutMs:5000}}; await execute({action:'suggest_cases',code:'test'},ctx); assert.ok(p!==null); });
  it('path validate_tests', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_validate_tests;}},config:{timeoutMs:5000}}; await execute({action:'validate_tests',tests:'test'},ctx); assert.ok(p!==null); });
});
