import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_exec_command = {"stdout":"output","exitCode":0};
const sample_upload_file = {"status":"uploaded","bytes":1024};
const sample_download_file = {"status":"downloaded","bytes":2048};
const sample_list_dir = {"files":[{"name":"file.txt","size":100,"type":"file"}]};
describe('ssh-client: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('ssh-client: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail exec_command', async()=>{ const r=await execute({action:'exec_command',host:'test',command:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail upload_file', async()=>{ const r=await execute({action:'upload_file',host:'test',localPath:'test',remotePath:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail download_file', async()=>{ const r=await execute({action:'download_file',host:'test',remotePath:'test',localPath:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail list_dir', async()=>{ const r=await execute({action:'list_dir',host:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('ssh-client: exec_command', ()=>{beforeEach(()=>{});
  it('exec_command ok', async()=>{ const r=await execute({action:'exec_command',host:'test',command:'test'},mockContext(sample_exec_command)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'exec_command'); });
  it('exec_command missing', async()=>{ const r=await execute({action:'exec_command'},mockContext(sample_exec_command)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('exec_command non-str', async()=>{ const r=await execute({action:'exec_command',host:123},mockContext(sample_exec_command)); assert.equal(r.metadata.success,false); });
});
describe('ssh-client: upload_file', ()=>{beforeEach(()=>{});
  it('upload_file ok', async()=>{ const r=await execute({action:'upload_file',host:'test',localPath:'test',remotePath:'test'},mockContext(sample_upload_file)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'upload_file'); });
  it('upload_file missing', async()=>{ const r=await execute({action:'upload_file'},mockContext(sample_upload_file)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('upload_file non-str', async()=>{ const r=await execute({action:'upload_file',host:123},mockContext(sample_upload_file)); assert.equal(r.metadata.success,false); });
});
describe('ssh-client: download_file', ()=>{beforeEach(()=>{});
  it('download_file ok', async()=>{ const r=await execute({action:'download_file',host:'test',remotePath:'test',localPath:'test'},mockContext(sample_download_file)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'download_file'); });
  it('download_file missing', async()=>{ const r=await execute({action:'download_file'},mockContext(sample_download_file)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('download_file non-str', async()=>{ const r=await execute({action:'download_file',host:123},mockContext(sample_download_file)); assert.equal(r.metadata.success,false); });
});
describe('ssh-client: list_dir', ()=>{beforeEach(()=>{});
  it('list_dir ok', async()=>{ const r=await execute({action:'list_dir',host:'test'},mockContext(sample_list_dir)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'list_dir'); });
  it('list_dir missing', async()=>{ const r=await execute({action:'list_dir'},mockContext(sample_list_dir)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('list_dir non-str', async()=>{ const r=await execute({action:'list_dir',host:123},mockContext(sample_list_dir)); assert.equal(r.metadata.success,false); });
});
describe('ssh-client: timeout', ()=>{beforeEach(()=>{});
  it('to exec_command', async()=>{ const r=await execute({action:'exec_command',host:'test',command:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to upload_file', async()=>{ const r=await execute({action:'upload_file',host:'test',localPath:'test',remotePath:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to download_file', async()=>{ const r=await execute({action:'download_file',host:'test',remotePath:'test',localPath:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to list_dir', async()=>{ const r=await execute({action:'list_dir',host:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('ssh-client: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'exec_command',host:'test',command:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'exec_command',host:'test',command:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('ssh-client: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('ssh-client: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('ssh-client: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('ssh-client: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('exec_command req', ()=>{ assert.equal(validate({action:'exec_command'}).valid,false); assert.equal(validate({action:'exec_command',host:'t',command:'t'}).valid,true); });
  it('upload_file req', ()=>{ assert.equal(validate({action:'upload_file'}).valid,false); assert.equal(validate({action:'upload_file',host:'t',localPath:'t',remotePath:'t'}).valid,true); });
  it('download_file req', ()=>{ assert.equal(validate({action:'download_file'}).valid,false); assert.equal(validate({action:'download_file',host:'t',remotePath:'t',localPath:'t'}).valid,true); });
  it('list_dir req', ()=>{ assert.equal(validate({action:'list_dir'}).valid,false); assert.equal(validate({action:'list_dir',host:'t'}).valid,true); });
});
describe('ssh-client: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'ssh-client');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('ssh-client: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_exec_command},config:{timeoutMs:5000}};const r=await execute({action:'exec_command',host:'test',command:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('ssh-client: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('ssh-client: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['exec_command','upload_file','download_file','list_dir']);});
});
describe('ssh-client: paths', ()=>{beforeEach(()=>{});
  it('path exec_command', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_exec_command;}},config:{timeoutMs:5000}}; await execute({action:'exec_command',host:'test',command:'test'},ctx); assert.ok(p!==null); });
  it('path upload_file', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_upload_file;}},config:{timeoutMs:5000}}; await execute({action:'upload_file',host:'test',localPath:'test',remotePath:'test'},ctx); assert.ok(p!==null); });
  it('path download_file', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_download_file;}},config:{timeoutMs:5000}}; await execute({action:'download_file',host:'test',remotePath:'test',localPath:'test'},ctx); assert.ok(p!==null); });
  it('path list_dir', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_list_dir;}},config:{timeoutMs:5000}}; await execute({action:'list_dir',host:'test'},ctx); assert.ok(p!==null); });
});
