import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_analyze_page = {"score":72,"issues":[{"type":"missing_meta","severity":"high"}],"title":"Page Title"};
const sample_check_keywords = {"density":{"keyword1":2.5,"keyword2":1.2},"suggestions":["related term"]};
const sample_get_backlinks = {"totalLinks":150,"links":[{"source":"example.com","anchor":"click here"}]};
const sample_check_speed = {"loadTime":2.5,"score":85,"suggestions":["compress images"]};
describe('seo-optimizer: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('seo-optimizer: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail analyze_page', async()=>{ const r=await execute({action:'analyze_page',url:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail check_keywords', async()=>{ const r=await execute({action:'check_keywords',url:'test',keywords:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_backlinks', async()=>{ const r=await execute({action:'get_backlinks',url:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail check_speed', async()=>{ const r=await execute({action:'check_speed',url:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('seo-optimizer: analyze_page', ()=>{beforeEach(()=>{});
  it('analyze_page ok', async()=>{ const r=await execute({action:'analyze_page',url:'test'},mockContext(sample_analyze_page)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'analyze_page'); });
  it('analyze_page missing', async()=>{ const r=await execute({action:'analyze_page'},mockContext(sample_analyze_page)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('analyze_page non-str', async()=>{ const r=await execute({action:'analyze_page',url:123},mockContext(sample_analyze_page)); assert.equal(r.metadata.success,false); });
});
describe('seo-optimizer: check_keywords', ()=>{beforeEach(()=>{});
  it('check_keywords ok', async()=>{ const r=await execute({action:'check_keywords',url:'test',keywords:'test'},mockContext(sample_check_keywords)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'check_keywords'); });
  it('check_keywords missing', async()=>{ const r=await execute({action:'check_keywords'},mockContext(sample_check_keywords)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('check_keywords non-str', async()=>{ const r=await execute({action:'check_keywords',url:123},mockContext(sample_check_keywords)); assert.equal(r.metadata.success,false); });
});
describe('seo-optimizer: get_backlinks', ()=>{beforeEach(()=>{});
  it('get_backlinks ok', async()=>{ const r=await execute({action:'get_backlinks',url:'test'},mockContext(sample_get_backlinks)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_backlinks'); });
  it('get_backlinks missing', async()=>{ const r=await execute({action:'get_backlinks'},mockContext(sample_get_backlinks)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('get_backlinks non-str', async()=>{ const r=await execute({action:'get_backlinks',url:123},mockContext(sample_get_backlinks)); assert.equal(r.metadata.success,false); });
});
describe('seo-optimizer: check_speed', ()=>{beforeEach(()=>{});
  it('check_speed ok', async()=>{ const r=await execute({action:'check_speed',url:'test'},mockContext(sample_check_speed)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'check_speed'); });
  it('check_speed missing', async()=>{ const r=await execute({action:'check_speed'},mockContext(sample_check_speed)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('check_speed non-str', async()=>{ const r=await execute({action:'check_speed',url:123},mockContext(sample_check_speed)); assert.equal(r.metadata.success,false); });
});
describe('seo-optimizer: timeout', ()=>{beforeEach(()=>{});
  it('to analyze_page', async()=>{ const r=await execute({action:'analyze_page',url:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to check_keywords', async()=>{ const r=await execute({action:'check_keywords',url:'test',keywords:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_backlinks', async()=>{ const r=await execute({action:'get_backlinks',url:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to check_speed', async()=>{ const r=await execute({action:'check_speed',url:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('seo-optimizer: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'analyze_page',url:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'analyze_page',url:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('seo-optimizer: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('seo-optimizer: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('seo-optimizer: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('seo-optimizer: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('analyze_page req', ()=>{ assert.equal(validate({action:'analyze_page'}).valid,false); assert.equal(validate({action:'analyze_page',url:'t'}).valid,true); });
  it('check_keywords req', ()=>{ assert.equal(validate({action:'check_keywords'}).valid,false); assert.equal(validate({action:'check_keywords',url:'t',keywords:'t'}).valid,true); });
  it('get_backlinks req', ()=>{ assert.equal(validate({action:'get_backlinks'}).valid,false); assert.equal(validate({action:'get_backlinks',url:'t'}).valid,true); });
  it('check_speed req', ()=>{ assert.equal(validate({action:'check_speed'}).valid,false); assert.equal(validate({action:'check_speed',url:'t'}).valid,true); });
});
describe('seo-optimizer: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'seo-optimizer');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('seo-optimizer: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_analyze_page},config:{timeoutMs:5000}};const r=await execute({action:'analyze_page',url:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('seo-optimizer: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('seo-optimizer: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['analyze_page','check_keywords','get_backlinks','check_speed']);});
});
describe('seo-optimizer: paths', ()=>{beforeEach(()=>{});
  it('path analyze_page', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_analyze_page;}},config:{timeoutMs:5000}}; await execute({action:'analyze_page',url:'test'},ctx); assert.ok(p!==null); });
  it('path check_keywords', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_check_keywords;}},config:{timeoutMs:5000}}; await execute({action:'check_keywords',url:'test',keywords:'test'},ctx); assert.ok(p!==null); });
  it('path get_backlinks', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_backlinks;}},config:{timeoutMs:5000}}; await execute({action:'get_backlinks',url:'test'},ctx); assert.ok(p!==null); });
  it('path check_speed', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_check_speed;}},config:{timeoutMs:5000}}; await execute({action:'check_speed',url:'test'},ctx); assert.ok(p!==null); });
});
