import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_get_interest = {"keyword":"AI","timeline":[{"date":"2024-01","value":85}]};
const sample_get_related = {"queries":[{"query":"machine learning","value":100}],"topics":[{"title":"Deep Learning","value":90}]};
const sample_compare_keywords = {"comparison":[{"keyword":"AI","avgInterest":85},{"keyword":"ML","avgInterest":60}]};
const sample_get_trending = {"trending":[{"title":"Breaking News","traffic":"500K+"}]};
describe('google-trends-api: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('google-trends-api: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail get_interest', async()=>{ const r=await execute({action:'get_interest',keyword:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_related', async()=>{ const r=await execute({action:'get_related',keyword:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail compare_keywords', async()=>{ const r=await execute({action:'compare_keywords',keywords:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_trending', async()=>{ const r=await execute({action:'get_trending'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('google-trends-api: get_interest', ()=>{beforeEach(()=>{});
  it('get_interest ok', async()=>{ const r=await execute({action:'get_interest',keyword:'test'},mockContext(sample_get_interest)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_interest'); });
  it('get_interest missing', async()=>{ const r=await execute({action:'get_interest'},mockContext(sample_get_interest)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('get_interest non-str', async()=>{ const r=await execute({action:'get_interest',keyword:123},mockContext(sample_get_interest)); assert.equal(r.metadata.success,false); });
});
describe('google-trends-api: get_related', ()=>{beforeEach(()=>{});
  it('get_related ok', async()=>{ const r=await execute({action:'get_related',keyword:'test'},mockContext(sample_get_related)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_related'); });
  it('get_related missing', async()=>{ const r=await execute({action:'get_related'},mockContext(sample_get_related)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('get_related non-str', async()=>{ const r=await execute({action:'get_related',keyword:123},mockContext(sample_get_related)); assert.equal(r.metadata.success,false); });
});
describe('google-trends-api: compare_keywords', ()=>{beforeEach(()=>{});
  it('compare_keywords ok', async()=>{ const r=await execute({action:'compare_keywords',keywords:'test'},mockContext(sample_compare_keywords)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'compare_keywords'); });
  it('compare_keywords missing', async()=>{ const r=await execute({action:'compare_keywords'},mockContext(sample_compare_keywords)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('compare_keywords non-str', async()=>{ const r=await execute({action:'compare_keywords',keywords:123},mockContext(sample_compare_keywords)); assert.equal(r.metadata.success,false); });
});
describe('google-trends-api: get_trending', ()=>{beforeEach(()=>{});
  it('get_trending ok', async()=>{ const r=await execute({action:'get_trending'},mockContext(sample_get_trending)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_trending'); });
});
describe('google-trends-api: timeout', ()=>{beforeEach(()=>{});
  it('to get_interest', async()=>{ const r=await execute({action:'get_interest',keyword:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_related', async()=>{ const r=await execute({action:'get_related',keyword:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to compare_keywords', async()=>{ const r=await execute({action:'compare_keywords',keywords:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_trending', async()=>{ const r=await execute({action:'get_trending'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('google-trends-api: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'get_interest',keyword:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'get_interest',keyword:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('google-trends-api: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('google-trends-api: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('google-trends-api: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('google-trends-api: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('get_interest req', ()=>{ assert.equal(validate({action:'get_interest'}).valid,false); assert.equal(validate({action:'get_interest',keyword:'t'}).valid,true); });
  it('get_related req', ()=>{ assert.equal(validate({action:'get_related'}).valid,false); assert.equal(validate({action:'get_related',keyword:'t'}).valid,true); });
  it('compare_keywords req', ()=>{ assert.equal(validate({action:'compare_keywords'}).valid,false); assert.equal(validate({action:'compare_keywords',keywords:'t'}).valid,true); });
  it('get_trending ok', ()=>{ assert.equal(validate({action:'get_trending'}).valid,true); });
});
describe('google-trends-api: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'google-trends-api');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('google-trends-api: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_get_interest},config:{timeoutMs:5000}};const r=await execute({action:'get_interest',keyword:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('google-trends-api: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('google-trends-api: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['get_interest','get_related','compare_keywords','get_trending']);});
});
describe('google-trends-api: paths', ()=>{beforeEach(()=>{});
  it('path get_interest', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_interest;}},config:{timeoutMs:5000}}; await execute({action:'get_interest',keyword:'test'},ctx); assert.ok(p!==null); });
  it('path get_related', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_related;}},config:{timeoutMs:5000}}; await execute({action:'get_related',keyword:'test'},ctx); assert.ok(p!==null); });
  it('path compare_keywords', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_compare_keywords;}},config:{timeoutMs:5000}}; await execute({action:'compare_keywords',keywords:'test'},ctx); assert.ok(p!==null); });
  it('path get_trending', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_trending;}},config:{timeoutMs:5000}}; await execute({action:'get_trending'},ctx); assert.ok(p!==null); });
});
