import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_compare_pdfs = {"identical":false,"diffCount":5,"pages":[{"page":1,"diffs":3}]};
const sample_get_text_diff = {"additions":["new text"],"deletions":["old text"],"changes":1};
const sample_get_visual_diff = {"diffImageUrl":"/output/diff-page1.png","changePercentage":12.5};
const sample_get_metadata_diff = {"diff":{"author":["Author A","Author B"],"pageCount":[10,12]}};
describe('pdf-compare: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('pdf-compare: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail compare_pdfs', async()=>{ const r=await execute({action:'compare_pdfs',file1:'test',file2:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_text_diff', async()=>{ const r=await execute({action:'get_text_diff',file1:'test',file2:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_visual_diff', async()=>{ const r=await execute({action:'get_visual_diff',file1:'test',file2:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_metadata_diff', async()=>{ const r=await execute({action:'get_metadata_diff',file1:'test',file2:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('pdf-compare: compare_pdfs', ()=>{beforeEach(()=>{});
  it('compare_pdfs ok', async()=>{ const r=await execute({action:'compare_pdfs',file1:'test',file2:'test'},mockContext(sample_compare_pdfs)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'compare_pdfs'); });
  it('compare_pdfs missing', async()=>{ const r=await execute({action:'compare_pdfs'},mockContext(sample_compare_pdfs)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('compare_pdfs non-str', async()=>{ const r=await execute({action:'compare_pdfs',file1:123},mockContext(sample_compare_pdfs)); assert.equal(r.metadata.success,false); });
});
describe('pdf-compare: get_text_diff', ()=>{beforeEach(()=>{});
  it('get_text_diff ok', async()=>{ const r=await execute({action:'get_text_diff',file1:'test',file2:'test'},mockContext(sample_get_text_diff)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_text_diff'); });
  it('get_text_diff missing', async()=>{ const r=await execute({action:'get_text_diff'},mockContext(sample_get_text_diff)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('get_text_diff non-str', async()=>{ const r=await execute({action:'get_text_diff',file1:123},mockContext(sample_get_text_diff)); assert.equal(r.metadata.success,false); });
});
describe('pdf-compare: get_visual_diff', ()=>{beforeEach(()=>{});
  it('get_visual_diff ok', async()=>{ const r=await execute({action:'get_visual_diff',file1:'test',file2:'test'},mockContext(sample_get_visual_diff)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_visual_diff'); });
  it('get_visual_diff missing', async()=>{ const r=await execute({action:'get_visual_diff'},mockContext(sample_get_visual_diff)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('get_visual_diff non-str', async()=>{ const r=await execute({action:'get_visual_diff',file1:123},mockContext(sample_get_visual_diff)); assert.equal(r.metadata.success,false); });
});
describe('pdf-compare: get_metadata_diff', ()=>{beforeEach(()=>{});
  it('get_metadata_diff ok', async()=>{ const r=await execute({action:'get_metadata_diff',file1:'test',file2:'test'},mockContext(sample_get_metadata_diff)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_metadata_diff'); });
  it('get_metadata_diff missing', async()=>{ const r=await execute({action:'get_metadata_diff'},mockContext(sample_get_metadata_diff)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('get_metadata_diff non-str', async()=>{ const r=await execute({action:'get_metadata_diff',file1:123},mockContext(sample_get_metadata_diff)); assert.equal(r.metadata.success,false); });
});
describe('pdf-compare: timeout', ()=>{beforeEach(()=>{});
  it('to compare_pdfs', async()=>{ const r=await execute({action:'compare_pdfs',file1:'test',file2:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_text_diff', async()=>{ const r=await execute({action:'get_text_diff',file1:'test',file2:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_visual_diff', async()=>{ const r=await execute({action:'get_visual_diff',file1:'test',file2:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_metadata_diff', async()=>{ const r=await execute({action:'get_metadata_diff',file1:'test',file2:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('pdf-compare: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'compare_pdfs',file1:'test',file2:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'compare_pdfs',file1:'test',file2:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('pdf-compare: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('pdf-compare: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('pdf-compare: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('pdf-compare: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('compare_pdfs req', ()=>{ assert.equal(validate({action:'compare_pdfs'}).valid,false); assert.equal(validate({action:'compare_pdfs',file1:'t',file2:'t'}).valid,true); });
  it('get_text_diff req', ()=>{ assert.equal(validate({action:'get_text_diff'}).valid,false); assert.equal(validate({action:'get_text_diff',file1:'t',file2:'t'}).valid,true); });
  it('get_visual_diff req', ()=>{ assert.equal(validate({action:'get_visual_diff'}).valid,false); assert.equal(validate({action:'get_visual_diff',file1:'t',file2:'t'}).valid,true); });
  it('get_metadata_diff req', ()=>{ assert.equal(validate({action:'get_metadata_diff'}).valid,false); assert.equal(validate({action:'get_metadata_diff',file1:'t',file2:'t'}).valid,true); });
});
describe('pdf-compare: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'pdf-compare');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('pdf-compare: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_compare_pdfs},config:{timeoutMs:5000}};const r=await execute({action:'compare_pdfs',file1:'test',file2:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('pdf-compare: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('pdf-compare: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['compare_pdfs','get_text_diff','get_visual_diff','get_metadata_diff']);});
});
describe('pdf-compare: paths', ()=>{beforeEach(()=>{});
  it('path compare_pdfs', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_compare_pdfs;}},config:{timeoutMs:5000}}; await execute({action:'compare_pdfs',file1:'test',file2:'test'},ctx); assert.ok(p!==null); });
  it('path get_text_diff', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_text_diff;}},config:{timeoutMs:5000}}; await execute({action:'get_text_diff',file1:'test',file2:'test'},ctx); assert.ok(p!==null); });
  it('path get_visual_diff', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_visual_diff;}},config:{timeoutMs:5000}}; await execute({action:'get_visual_diff',file1:'test',file2:'test'},ctx); assert.ok(p!==null); });
  it('path get_metadata_diff', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_metadata_diff;}},config:{timeoutMs:5000}}; await execute({action:'get_metadata_diff',file1:'test',file2:'test'},ctx); assert.ok(p!==null); });
});
