import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_geocode = {"results":[{"formatted_address":"1600 Amphitheatre Pkwy","geometry":{"location":{"lat":37.422,"lng":-122.084}}}]};
const sample_search_places = {"results":[{"name":"Coffee Shop","place_id":"ChIJ123","rating":4.5}]};
const sample_get_directions = {"routes":[{"legs":[{"distance":{"text":"10 km"},"duration":{"text":"15 min"}}]}]};
const sample_get_place_details = {"result":{"name":"Coffee Shop","formatted_phone_number":"+1-234","opening_hours":{"open_now":true}}};
describe('google-maps-api: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('google-maps-api: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail geocode', async()=>{ const r=await execute({action:'geocode',address:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail search_places', async()=>{ const r=await execute({action:'search_places',query:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_directions', async()=>{ const r=await execute({action:'get_directions',origin:'test',destination:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_place_details', async()=>{ const r=await execute({action:'get_place_details',placeId:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('google-maps-api: geocode', ()=>{beforeEach(()=>{});
  it('geocode ok', async()=>{ const r=await execute({action:'geocode',address:'test'},mockContext(sample_geocode)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'geocode'); });
  it('geocode missing', async()=>{ const r=await execute({action:'geocode'},mockContext(sample_geocode)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('geocode non-str', async()=>{ const r=await execute({action:'geocode',address:123},mockContext(sample_geocode)); assert.equal(r.metadata.success,false); });
});
describe('google-maps-api: search_places', ()=>{beforeEach(()=>{});
  it('search_places ok', async()=>{ const r=await execute({action:'search_places',query:'test'},mockContext(sample_search_places)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'search_places'); });
  it('search_places missing', async()=>{ const r=await execute({action:'search_places'},mockContext(sample_search_places)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('search_places non-str', async()=>{ const r=await execute({action:'search_places',query:123},mockContext(sample_search_places)); assert.equal(r.metadata.success,false); });
});
describe('google-maps-api: get_directions', ()=>{beforeEach(()=>{});
  it('get_directions ok', async()=>{ const r=await execute({action:'get_directions',origin:'test',destination:'test'},mockContext(sample_get_directions)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_directions'); });
  it('get_directions missing', async()=>{ const r=await execute({action:'get_directions'},mockContext(sample_get_directions)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('get_directions non-str', async()=>{ const r=await execute({action:'get_directions',origin:123},mockContext(sample_get_directions)); assert.equal(r.metadata.success,false); });
});
describe('google-maps-api: get_place_details', ()=>{beforeEach(()=>{});
  it('get_place_details ok', async()=>{ const r=await execute({action:'get_place_details',placeId:'test'},mockContext(sample_get_place_details)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_place_details'); });
  it('get_place_details missing', async()=>{ const r=await execute({action:'get_place_details'},mockContext(sample_get_place_details)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('get_place_details non-str', async()=>{ const r=await execute({action:'get_place_details',placeId:123},mockContext(sample_get_place_details)); assert.equal(r.metadata.success,false); });
});
describe('google-maps-api: timeout', ()=>{beforeEach(()=>{});
  it('to geocode', async()=>{ const r=await execute({action:'geocode',address:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to search_places', async()=>{ const r=await execute({action:'search_places',query:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_directions', async()=>{ const r=await execute({action:'get_directions',origin:'test',destination:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_place_details', async()=>{ const r=await execute({action:'get_place_details',placeId:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('google-maps-api: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'geocode',address:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'geocode',address:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('google-maps-api: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('google-maps-api: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('google-maps-api: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('google-maps-api: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('geocode req', ()=>{ assert.equal(validate({action:'geocode'}).valid,false); assert.equal(validate({action:'geocode',address:'t'}).valid,true); });
  it('search_places req', ()=>{ assert.equal(validate({action:'search_places'}).valid,false); assert.equal(validate({action:'search_places',query:'t'}).valid,true); });
  it('get_directions req', ()=>{ assert.equal(validate({action:'get_directions'}).valid,false); assert.equal(validate({action:'get_directions',origin:'t',destination:'t'}).valid,true); });
  it('get_place_details req', ()=>{ assert.equal(validate({action:'get_place_details'}).valid,false); assert.equal(validate({action:'get_place_details',placeId:'t'}).valid,true); });
});
describe('google-maps-api: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'google-maps-api');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('google-maps-api: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_geocode},config:{timeoutMs:5000}};const r=await execute({action:'geocode',address:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('google-maps-api: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('google-maps-api: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['geocode','search_places','get_directions','get_place_details']);});
});
describe('google-maps-api: paths', ()=>{beforeEach(()=>{});
  it('path geocode', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_geocode;}},config:{timeoutMs:5000}}; await execute({action:'geocode',address:'test'},ctx); assert.ok(p!==null); });
  it('path search_places', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_search_places;}},config:{timeoutMs:5000}}; await execute({action:'search_places',query:'test'},ctx); assert.ok(p!==null); });
  it('path get_directions', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_directions;}},config:{timeoutMs:5000}}; await execute({action:'get_directions',origin:'test',destination:'test'},ctx); assert.ok(p!==null); });
  it('path get_place_details', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_place_details;}},config:{timeoutMs:5000}}; await execute({action:'get_place_details',placeId:'test'},ctx); assert.ok(p!==null); });
});
