import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_analyze_image = {"description":"A cat sitting on a table","labels":["cat","table","indoor"],"confidence":0.95};
const sample_detect_objects = {"objects":[{"label":"cat","bbox":[10,20,100,200],"confidence":0.92}]};
const sample_extract_text = {"text":"Extracted text content","blocks":[{"text":"Block 1","confidence":0.98}]};
const sample_compare_images = {"similarity":0.85,"differences":["color","position"]};
describe('vision-model: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('vision-model: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail analyze_image', async()=>{ const r=await execute({action:'analyze_image',imageUrl:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail detect_objects', async()=>{ const r=await execute({action:'detect_objects',imageUrl:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail extract_text', async()=>{ const r=await execute({action:'extract_text',imageUrl:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail compare_images', async()=>{ const r=await execute({action:'compare_images',imageUrl1:'test',imageUrl2:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('vision-model: analyze_image', ()=>{beforeEach(()=>{});
  it('analyze_image ok', async()=>{ const r=await execute({action:'analyze_image',imageUrl:'test'},mockContext(sample_analyze_image)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'analyze_image'); });
  it('analyze_image missing', async()=>{ const r=await execute({action:'analyze_image'},mockContext(sample_analyze_image)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('analyze_image non-str', async()=>{ const r=await execute({action:'analyze_image',imageUrl:123},mockContext(sample_analyze_image)); assert.equal(r.metadata.success,false); });
});
describe('vision-model: detect_objects', ()=>{beforeEach(()=>{});
  it('detect_objects ok', async()=>{ const r=await execute({action:'detect_objects',imageUrl:'test'},mockContext(sample_detect_objects)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'detect_objects'); });
  it('detect_objects missing', async()=>{ const r=await execute({action:'detect_objects'},mockContext(sample_detect_objects)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('detect_objects non-str', async()=>{ const r=await execute({action:'detect_objects',imageUrl:123},mockContext(sample_detect_objects)); assert.equal(r.metadata.success,false); });
});
describe('vision-model: extract_text', ()=>{beforeEach(()=>{});
  it('extract_text ok', async()=>{ const r=await execute({action:'extract_text',imageUrl:'test'},mockContext(sample_extract_text)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'extract_text'); });
  it('extract_text missing', async()=>{ const r=await execute({action:'extract_text'},mockContext(sample_extract_text)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('extract_text non-str', async()=>{ const r=await execute({action:'extract_text',imageUrl:123},mockContext(sample_extract_text)); assert.equal(r.metadata.success,false); });
});
describe('vision-model: compare_images', ()=>{beforeEach(()=>{});
  it('compare_images ok', async()=>{ const r=await execute({action:'compare_images',imageUrl1:'test',imageUrl2:'test'},mockContext(sample_compare_images)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'compare_images'); });
  it('compare_images missing', async()=>{ const r=await execute({action:'compare_images'},mockContext(sample_compare_images)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('compare_images non-str', async()=>{ const r=await execute({action:'compare_images',imageUrl1:123},mockContext(sample_compare_images)); assert.equal(r.metadata.success,false); });
});
describe('vision-model: timeout', ()=>{beforeEach(()=>{});
  it('to analyze_image', async()=>{ const r=await execute({action:'analyze_image',imageUrl:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to detect_objects', async()=>{ const r=await execute({action:'detect_objects',imageUrl:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to extract_text', async()=>{ const r=await execute({action:'extract_text',imageUrl:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to compare_images', async()=>{ const r=await execute({action:'compare_images',imageUrl1:'test',imageUrl2:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('vision-model: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'analyze_image',imageUrl:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'analyze_image',imageUrl:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('vision-model: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('vision-model: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('vision-model: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('vision-model: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('analyze_image req', ()=>{ assert.equal(validate({action:'analyze_image'}).valid,false); assert.equal(validate({action:'analyze_image',imageUrl:'t'}).valid,true); });
  it('detect_objects req', ()=>{ assert.equal(validate({action:'detect_objects'}).valid,false); assert.equal(validate({action:'detect_objects',imageUrl:'t'}).valid,true); });
  it('extract_text req', ()=>{ assert.equal(validate({action:'extract_text'}).valid,false); assert.equal(validate({action:'extract_text',imageUrl:'t'}).valid,true); });
  it('compare_images req', ()=>{ assert.equal(validate({action:'compare_images'}).valid,false); assert.equal(validate({action:'compare_images',imageUrl1:'t',imageUrl2:'t'}).valid,true); });
});
describe('vision-model: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'vision-model');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('vision-model: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_analyze_image},config:{timeoutMs:5000}};const r=await execute({action:'analyze_image',imageUrl:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('vision-model: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('vision-model: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['analyze_image','detect_objects','extract_text','compare_images']);});
});
describe('vision-model: paths', ()=>{beforeEach(()=>{});
  it('path analyze_image', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_analyze_image;}},config:{timeoutMs:5000}}; await execute({action:'analyze_image',imageUrl:'test'},ctx); assert.ok(p!==null); });
  it('path detect_objects', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_detect_objects;}},config:{timeoutMs:5000}}; await execute({action:'detect_objects',imageUrl:'test'},ctx); assert.ok(p!==null); });
  it('path extract_text', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_extract_text;}},config:{timeoutMs:5000}}; await execute({action:'extract_text',imageUrl:'test'},ctx); assert.ok(p!==null); });
  it('path compare_images', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_compare_images;}},config:{timeoutMs:5000}}; await execute({action:'compare_images',imageUrl1:'test',imageUrl2:'test'},ctx); assert.ok(p!==null); });
});
