import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_generate = {"response":"Generated text","model":"llama2","done":true};
const sample_chat = {"message":{"role":"assistant","content":"Response text"},"done":true};
const sample_list_models = {"models":[{"name":"llama2","size":3800000000}]};
const sample_pull_model = {"status":"success"};
describe('ollama-local-llm: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('ollama-local-llm: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail generate', async()=>{ const r=await execute({action:'generate',model:'test',prompt:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail chat', async()=>{ const r=await execute({action:'chat',model:'test',message:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail list_models', async()=>{ const r=await execute({action:'list_models'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail pull_model', async()=>{ const r=await execute({action:'pull_model',model:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('ollama-local-llm: generate', ()=>{beforeEach(()=>{});
  it('generate ok', async()=>{ const r=await execute({action:'generate',model:'test',prompt:'test'},mockContext(sample_generate)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'generate'); });
  it('generate missing', async()=>{ const r=await execute({action:'generate'},mockContext(sample_generate)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('generate non-str', async()=>{ const r=await execute({action:'generate',model:123},mockContext(sample_generate)); assert.equal(r.metadata.success,false); });
});
describe('ollama-local-llm: chat', ()=>{beforeEach(()=>{});
  it('chat ok', async()=>{ const r=await execute({action:'chat',model:'test',message:'test'},mockContext(sample_chat)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'chat'); });
  it('chat missing', async()=>{ const r=await execute({action:'chat'},mockContext(sample_chat)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('chat non-str', async()=>{ const r=await execute({action:'chat',model:123},mockContext(sample_chat)); assert.equal(r.metadata.success,false); });
});
describe('ollama-local-llm: list_models', ()=>{beforeEach(()=>{});
  it('list_models ok', async()=>{ const r=await execute({action:'list_models'},mockContext(sample_list_models)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'list_models'); });
});
describe('ollama-local-llm: pull_model', ()=>{beforeEach(()=>{});
  it('pull_model ok', async()=>{ const r=await execute({action:'pull_model',model:'test'},mockContext(sample_pull_model)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'pull_model'); });
  it('pull_model missing', async()=>{ const r=await execute({action:'pull_model'},mockContext(sample_pull_model)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('pull_model non-str', async()=>{ const r=await execute({action:'pull_model',model:123},mockContext(sample_pull_model)); assert.equal(r.metadata.success,false); });
});
describe('ollama-local-llm: timeout', ()=>{beforeEach(()=>{});
  it('to generate', async()=>{ const r=await execute({action:'generate',model:'test',prompt:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to chat', async()=>{ const r=await execute({action:'chat',model:'test',message:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to list_models', async()=>{ const r=await execute({action:'list_models'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to pull_model', async()=>{ const r=await execute({action:'pull_model',model:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('ollama-local-llm: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'generate',model:'test',prompt:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'generate',model:'test',prompt:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('ollama-local-llm: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('ollama-local-llm: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('ollama-local-llm: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('ollama-local-llm: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('generate req', ()=>{ assert.equal(validate({action:'generate'}).valid,false); assert.equal(validate({action:'generate',model:'t',prompt:'t'}).valid,true); });
  it('chat req', ()=>{ assert.equal(validate({action:'chat'}).valid,false); assert.equal(validate({action:'chat',model:'t',message:'t'}).valid,true); });
  it('list_models ok', ()=>{ assert.equal(validate({action:'list_models'}).valid,true); });
  it('pull_model req', ()=>{ assert.equal(validate({action:'pull_model'}).valid,false); assert.equal(validate({action:'pull_model',model:'t'}).valid,true); });
});
describe('ollama-local-llm: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'ollama-local-llm');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('ollama-local-llm: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_generate},config:{timeoutMs:5000}};const r=await execute({action:'generate',model:'test',prompt:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('ollama-local-llm: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('ollama-local-llm: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['generate','chat','list_models','pull_model']);});
});
describe('ollama-local-llm: paths', ()=>{beforeEach(()=>{});
  it('path generate', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_generate;}},config:{timeoutMs:5000}}; await execute({action:'generate',model:'test',prompt:'test'},ctx); assert.ok(p!==null); });
  it('path chat', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_chat;}},config:{timeoutMs:5000}}; await execute({action:'chat',model:'test',message:'test'},ctx); assert.ok(p!==null); });
  it('path list_models', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_list_models;}},config:{timeoutMs:5000}}; await execute({action:'list_models'},ctx); assert.ok(p!==null); });
  it('path pull_model', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_pull_model;}},config:{timeoutMs:5000}}; await execute({action:'pull_model',model:'test'},ctx); assert.ok(p!==null); });
});
