import assert from 'node:assert/strict';
import { describe, it, beforeEach } from 'node:test';
import { execute, validate, meta, getClient, providerNotConfiguredError, resolveTimeout, requestWithTimeout, redactSensitive, validateNonEmptyString, VALID_ACTIONS, DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS } from '../handler.js';
function mockContext(r,c){ return {providerClient:{request:async()=>r},config:c||{timeoutMs:5000}}; }
function mockContextError(e){ return {providerClient:{request:async()=>{throw e;}},config:{timeoutMs:1000}}; }
function mockContextTimeout(){ return {providerClient:{request:async()=>{const e=new Error('aborted');e.name='AbortError';throw e;}},config:{timeoutMs:100}}; }
const sample_audit_deps = {"vulnerabilities":[{"name":"lodash","severity":"high","fixAvailable":true}],"total":1};
const sample_get_advisories = {"advisories":[{"id":"GHSA-123","title":"Prototype Pollution","severity":"critical"}]};
const sample_check_license = {"issues":[{"package":"gpl-lib","license":"GPL-3.0","severity":"warning"}]};
const sample_fix_vulnerabilities = {"fixed":3,"remaining":0,"changes":[{"package":"lodash","from":"4.17.20","to":"4.17.21"}]};
describe('npm-audit-snyk: action validation', ()=>{beforeEach(()=>{});
  it('reject invalid', async()=>{const r=await execute({action:'invalid'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_ACTION');});
  it('reject missing', async()=>{const r=await execute({},{}); assert.equal(r.metadata.success,false);});
  it('reject null', async()=>{const r=await execute(null,{}); assert.equal(r.metadata.success,false);});
  it('reject undef', async()=>{const r=await execute(undefined,{}); assert.equal(r.metadata.success,false);});
  it('list actions', async()=>{const r=await execute({action:'bad'},{}); for(const a of VALID_ACTIONS) assert.ok(r.result.includes(a));});
});
describe('npm-audit-snyk: PROVIDER_NOT_CONFIGURED', ()=>{beforeEach(()=>{});
  it('fail audit_deps', async()=>{ const r=await execute({action:'audit_deps',packageJson:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail get_advisories', async()=>{ const r=await execute({action:'get_advisories',package:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail check_license', async()=>{ const r=await execute({action:'check_license',packageJson:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
  it('fail fix_vulnerabilities', async()=>{ const r=await execute({action:'fix_vulnerabilities',packageJson:'test'},{}); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error.code,'PROVIDER_NOT_CONFIGURED'); });
});
describe('npm-audit-snyk: audit_deps', ()=>{beforeEach(()=>{});
  it('audit_deps ok', async()=>{ const r=await execute({action:'audit_deps',packageJson:'test'},mockContext(sample_audit_deps)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'audit_deps'); });
  it('audit_deps missing', async()=>{ const r=await execute({action:'audit_deps'},mockContext(sample_audit_deps)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('audit_deps non-str', async()=>{ const r=await execute({action:'audit_deps',packageJson:123},mockContext(sample_audit_deps)); assert.equal(r.metadata.success,false); });
});
describe('npm-audit-snyk: get_advisories', ()=>{beforeEach(()=>{});
  it('get_advisories ok', async()=>{ const r=await execute({action:'get_advisories',package:'test'},mockContext(sample_get_advisories)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'get_advisories'); });
  it('get_advisories missing', async()=>{ const r=await execute({action:'get_advisories'},mockContext(sample_get_advisories)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('get_advisories non-str', async()=>{ const r=await execute({action:'get_advisories',package:123},mockContext(sample_get_advisories)); assert.equal(r.metadata.success,false); });
});
describe('npm-audit-snyk: check_license', ()=>{beforeEach(()=>{});
  it('check_license ok', async()=>{ const r=await execute({action:'check_license',packageJson:'test'},mockContext(sample_check_license)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'check_license'); });
  it('check_license missing', async()=>{ const r=await execute({action:'check_license'},mockContext(sample_check_license)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('check_license non-str', async()=>{ const r=await execute({action:'check_license',packageJson:123},mockContext(sample_check_license)); assert.equal(r.metadata.success,false); });
});
describe('npm-audit-snyk: fix_vulnerabilities', ()=>{beforeEach(()=>{});
  it('fix_vulnerabilities ok', async()=>{ const r=await execute({action:'fix_vulnerabilities',packageJson:'test'},mockContext(sample_fix_vulnerabilities)); assert.equal(r.metadata.success,true); assert.equal(r.metadata.action,'fix_vulnerabilities'); });
  it('fix_vulnerabilities missing', async()=>{ const r=await execute({action:'fix_vulnerabilities'},mockContext(sample_fix_vulnerabilities)); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'INVALID_INPUT'); });
  it('fix_vulnerabilities non-str', async()=>{ const r=await execute({action:'fix_vulnerabilities',packageJson:123},mockContext(sample_fix_vulnerabilities)); assert.equal(r.metadata.success,false); });
});
describe('npm-audit-snyk: timeout', ()=>{beforeEach(()=>{});
  it('to audit_deps', async()=>{ const r=await execute({action:'audit_deps',packageJson:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to get_advisories', async()=>{ const r=await execute({action:'get_advisories',package:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to check_license', async()=>{ const r=await execute({action:'check_license',packageJson:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
  it('to fix_vulnerabilities', async()=>{ const r=await execute({action:'fix_vulnerabilities',packageJson:'test'},mockContextTimeout()); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'TIMEOUT'); });
});
describe('npm-audit-snyk: network errors', ()=>{beforeEach(()=>{});
  it('UPSTREAM_ERROR', async()=>{const r=await execute({action:'audit_deps',packageJson:'test'},mockContextError(new Error('fail'))); assert.equal(r.metadata.success,false); assert.equal(r.metadata.error,'UPSTREAM_ERROR');});
  it('include msg', async()=>{const r=await execute({action:'audit_deps',packageJson:'test'},mockContextError(new Error('fail'))); assert.ok(r.result.includes('fail'));});
});
describe('npm-audit-snyk: getClient', ()=>{beforeEach(()=>{});
  it('prefer provider', ()=>{assert.equal(getClient({providerClient:{request:()=>{}},gatewayClient:{request:()=>{}}}).type,'provider');});
  it('fallback', ()=>{assert.equal(getClient({gatewayClient:{request:()=>{}}}).type,'gateway');});
  it('null', ()=>{assert.equal(getClient({}),null);});
  it('null undef', ()=>{assert.equal(getClient(undefined),null);});
});
describe('npm-audit-snyk: redactSensitive', ()=>{beforeEach(()=>{});
  it('redact', ()=>{assert.ok(redactSensitive('api_key: test_key_val').includes('[REDACTED]'));});
  it('clean', ()=>{assert.equal(redactSensitive('clean'),'clean');});
  it('non-str', ()=>{assert.equal(redactSensitive(42),42);});
});
describe('npm-audit-snyk: resolveTimeout', ()=>{beforeEach(()=>{});
  it('def', ()=>{assert.equal(resolveTimeout({}),DEFAULT_TIMEOUT_MS);});
  it('undef', ()=>{assert.equal(resolveTimeout(undefined),DEFAULT_TIMEOUT_MS);});
  it('custom', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:60000}}),60000);});
  it('cap', ()=>{assert.equal(resolveTimeout({config:{timeoutMs:999999}}),MAX_TIMEOUT_MS);});
  it('D=30000', ()=>{assert.equal(DEFAULT_TIMEOUT_MS,30000);});
  it('M=120000', ()=>{assert.equal(MAX_TIMEOUT_MS,120000);});
});
describe('npm-audit-snyk: validate()', ()=>{beforeEach(()=>{});
  it('reject invalid', ()=>{assert.equal(validate({action:'bad'}).valid,false);});
  it('reject null', ()=>{assert.equal(validate(null).valid,false);});
  it('audit_deps req', ()=>{ assert.equal(validate({action:'audit_deps'}).valid,false); assert.equal(validate({action:'audit_deps',packageJson:'t'}).valid,true); });
  it('get_advisories req', ()=>{ assert.equal(validate({action:'get_advisories'}).valid,false); assert.equal(validate({action:'get_advisories',package:'t'}).valid,true); });
  it('check_license req', ()=>{ assert.equal(validate({action:'check_license'}).valid,false); assert.equal(validate({action:'check_license',packageJson:'t'}).valid,true); });
  it('fix_vulnerabilities req', ()=>{ assert.equal(validate({action:'fix_vulnerabilities'}).valid,false); assert.equal(validate({action:'fix_vulnerabilities',packageJson:'t'}).valid,true); });
});
describe('npm-audit-snyk: meta', ()=>{beforeEach(()=>{});
  it('name', ()=>{assert.equal(meta.name,'npm-audit-snyk');});
  it('version', ()=>{assert.equal(meta.version,'1.0.0');});
  it('actions', ()=>{assert.equal(meta.actions.length,4);});
});
describe('npm-audit-snyk: gateway', ()=>{beforeEach(()=>{});
  it('use gateway', async()=>{const ctx={gatewayClient:{request:async()=>sample_audit_deps},config:{timeoutMs:5000}};const r=await execute({action:'audit_deps',packageJson:'test'},ctx);assert.equal(r.metadata.success,true);});
});
describe('npm-audit-snyk: providerNotConfiguredError', ()=>{beforeEach(()=>{});
  it('false', ()=>{assert.equal(providerNotConfiguredError().metadata.success,false);});
  it('code', ()=>{assert.equal(providerNotConfiguredError().metadata.error.code,'PROVIDER_NOT_CONFIGURED');});
});
describe('npm-audit-snyk: constants', ()=>{beforeEach(()=>{});
  it('VALID_ACTIONS', ()=>{assert.deepEqual(VALID_ACTIONS,['audit_deps','get_advisories','check_license','fix_vulnerabilities']);});
});
describe('npm-audit-snyk: paths', ()=>{beforeEach(()=>{});
  it('path audit_deps', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_audit_deps;}},config:{timeoutMs:5000}}; await execute({action:'audit_deps',packageJson:'test'},ctx); assert.ok(p!==null); });
  it('path get_advisories', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_get_advisories;}},config:{timeoutMs:5000}}; await execute({action:'get_advisories',package:'test'},ctx); assert.ok(p!==null); });
  it('path check_license', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_check_license;}},config:{timeoutMs:5000}}; await execute({action:'check_license',packageJson:'test'},ctx); assert.ok(p!==null); });
  it('path fix_vulnerabilities', async()=>{ let p=null; const ctx={providerClient:{request:async(m,pa)=>{p=pa;return sample_fix_vulnerabilities;}},config:{timeoutMs:5000}}; await execute({action:'fix_vulnerabilities',packageJson:'test'},ctx); assert.ok(p!==null); });
});
